// English version of Finnish harbors and marinas database
// Comprehensive collection of coastal and inland harbors across Finland

export const harbors = [
  {
    id: 1,
    name: "Elisaari",
    language: "en",
    coordinates: { lat: 60.0167, lng: 23.9333 },
    region: "Western Uusimaa",
    type: ["Guest Marina", "Nature Harbor"],
    notableFeature: "Beautiful island with a restaurant and nature trails",
    description:
      "Elisaari is a popular guest marina in the western archipelago of Uusimaa. The island offers beautiful nature trails, a restaurant, and sauna facilities for visitors. It's a peaceful destination with good protection from winds.",
    hints: [
      "This harbor is located on an island in Western Uusimaa",
      "The island has a restaurant and nature trails",
      "It's a popular destination for family boating trips",
      "The name starts with 'E'",
      "It's located near Inkoo",
    ],
  },
  {
    id: 2,
    name: "Örö",
    language: "en",
    coordinates: { lat: 59.8089, lng: 22.3347 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Historical"],
    notableFeature: "Former military island with unique nature and historical fortifications",
    description:
      "Örö is a fascinating former military island in the outer archipelago that was opened to the public in 2015. It features rare flora, historical coastal artillery fortifications, and a guest harbor with modern facilities.",
    hints: [
      "This harbor is on a former military island",
      "It's located in the Archipelago Sea National Park",
      "The island has rare flora and coastal artillery fortifications",
      "The name is very short",
      "It starts with the letter 'Ö'",
    ],
  },
  {
    id: 3,
    name: "Jurmo",
    language: "en",
    coordinates: { lat: 59.8272, lng: 21.5772 },
    region: "Outer Archipelago Sea",
    type: ["Guest Marina", "Traditional"],
    notableFeature: "Remote island with unique geology and traditional archipelago village",
    description:
      "Jurmo is a remote, barren island in the outer archipelago with a distinctive landscape formed by ice age glaciers. It has a small traditional village, a guest harbor, and is known for its unique nature and bird watching opportunities.",
    hints: [
      "This harbor is on a remote, barren island in the outer archipelago",
      "The island has a distinctive landscape formed by ice age glaciers",
      "It's known for bird watching and unique nature",
      "The island has a small traditional village",
      "The name rhymes with 'Turmo'",
    ],
  },
  {
    id: 4,
    name: "Päijänne Marina",
    language: "en",
    coordinates: { lat: 61.6167, lng: 25.5667 },
    region: "Lake Päijänne",
    type: ["Inland Marina", "Lake Harbor"],
    notableFeature: "Large marina on Finland's second largest lake",
    description:
      "Located on the shores of Lake Päijänne, this marina serves as a hub for inland boaters exploring Finland's second largest lake. It offers comprehensive services including fuel, maintenance, and a restaurant.",
    hints: [
      "This marina is located on Finland's second largest lake",
      "It's a popular starting point for exploring the national park nearby",
      "The lake shares its name with the marina",
      "It's located in central Finland",
      "The name starts with 'P'",
    ],
  },
  {
    id: 5,
    name: "Seili",
    language: "en",
    coordinates: { lat: 60.2361, lng: 21.9444 },
    region: "Inner Archipelago Sea",
    type: ["Guest Marina", "Historical"],
    notableFeature: "Former leper hospital island with a wooden church and research station",
    description:
      "Seili (Själö in Swedish) has a dark history as a former leper colony and mental hospital island. Today it houses a biological research station and offers a guest marina for visitors. The wooden church and old hospital buildings tell the island's fascinating history.",
    hints: [
      "This harbor is on an island with a dark history as a former leper colony",
      "Today it houses a biological research station",
      "It has a wooden church and old hospital buildings",
      "The island's name is different in Finnish and Swedish",
      "In Finnish, it starts with 'S' and has 5 letters",
    ],
  },
  {
    id: 6,
    name: "Utö",
    language: "en",
    coordinates: { lat: 59.7833, lng: 21.3667 },
    region: "Outer Archipelago Sea",
    type: ["Guest Marina", "Lighthouse Island"],
    notableFeature: "Finland's southernmost year-round inhabited island with a historic lighthouse",
    description:
      "Utö is Finland's southernmost year-round inhabited island, featuring a historic lighthouse, a small village, and a guest marina. The island has a rich maritime history and offers a glimpse into the authentic life of the outer archipelago.",
    hints: [
      "This harbor is on Finland's southernmost year-round inhabited island",
      "The island features a historic lighthouse",
      "It has a rich maritime history and a small village",
      "The name is very short - only three letters",
      "It starts with 'U'",
    ],
  },
  {
    id: 7,
    name: "Saimaa Harbor",
    language: "en",
    coordinates: { lat: 61.8667, lng: 28.8833 },
    region: "Lake Saimaa",
    type: ["Inland Marina", "Lake Harbor"],
    notableFeature: "Marina on Finland's largest lake, home to endangered Saimaa ringed seals",
    description:
      "This harbor is located on Lake Saimaa, Finland's largest lake and home to the endangered Saimaa ringed seal. The marina offers services for boaters exploring the vast Saimaa lake system with its thousands of islands.",
    hints: [
      "This marina is located on Finland's largest lake",
      "The lake is home to an endangered species of freshwater seal",
      "The lake system has thousands of islands and islets",
      "It's located in eastern Finland",
      "The name starts with 'S'",
    ],
  },
  {
    id: 8,
    name: "Kökar",
    language: "en",
    coordinates: { lat: 59.9167, lng: 20.9 },
    region: "Åland Archipelago",
    type: ["Guest Marina", "Cultural"],
    notableFeature: "Remote Åland island with medieval monastery ruins",
    description:
      "Kökar is one of the most remote inhabited islands in the Åland archipelago. It features medieval Franciscan monastery ruins, a beautiful church, and several guest harbors. The island has a rich fishing heritage and unique cultural traditions.",
    hints: [
      "This harbor is on one of the most remote inhabited islands in the Åland archipelago",
      "The island features medieval Franciscan monastery ruins",
      "It has a rich fishing heritage and unique cultural traditions",
      "The name is five letters long",
      "It starts with 'K' and has an 'ö' in it",
    ],
  },
  {
    id: 9,
    name: "Inari Marina",
    language: "en",
    coordinates: { lat: 68.9, lng: 27.0333 },
    region: "Lapland",
    type: ["Inland Marina", "Arctic Harbor"],
    notableFeature: "Northernmost major marina in Finland, on Lake Inari",
    description:
      "Located on the shores of Lake Inari in Finnish Lapland, this is one of the northernmost marinas in Finland. It serves as a base for exploring the wilderness of northern Lapland and the sacred sites of the indigenous Sámi people.",
    hints: [
      "This marina is one of the northernmost in Finland",
      "It's located on a large lake in Lapland",
      "The lake and marina share the same name",
      "It's near sacred sites of the indigenous Sámi people",
      "The name starts with 'I'",
    ],
  },
  {
    id: 10,
    name: "Jussarö",
    language: "en",
    coordinates: { lat: 59.8333, lng: 23.5667 },
    region: "Western Gulf of Finland",
    type: ["Guest Marina", "Mining Island"],
    notableFeature: "Former iron mining island with ghost town and lighthouse",
    description:
      "Jussarö is a fascinating island with an abandoned iron mine, a ghost town, and a lighthouse. Now part of a national park, it offers a guest marina for visitors exploring its unique industrial history and nature trails.",
    hints: [
      "This harbor is on an island with an abandoned iron mine and ghost town",
      "It features a lighthouse and is now part of a national park",
      "The island has a unique industrial history and nature trails",
      "The name ends with 'ö'",
      "It starts with 'J'",
    ],
  },
  {
    id: 11,
    name: "Nötö",
    language: "en",
    coordinates: { lat: 59.95, lng: 21.7667 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Traditional"],
    notableFeature: "Traditional archipelago village with wooden houses and a stone church",
    description:
      "Nötö is one of the larger islands in the southern Archipelago Sea with a traditional village, wooden houses, and a stone church from the 1750s. The guest harbor offers good services and is a popular stop for archipelago cruisers.",
    hints: [
      "This harbor is on one of the larger islands in the southern Archipelago Sea",
      "It has a traditional village with wooden houses",
      "The island features a stone church from the 1750s",
      "The name means 'Nut Island' in Swedish",
      "It starts with 'N' and ends with 'ö'",
    ],
  },
  {
    id: 12,
    name: "Pielavesi Harbor",
    language: "en",
    coordinates: { lat: 63.2333, lng: 26.75 },
    region: "Northern Savonia",
    type: ["Inland Marina", "Lake Harbor"],
    notableFeature: "Charming small town harbor in the Finnish lake district",
    description:
      "Located in the small town of Pielavesi in the Finnish lake district, this harbor serves local boaters and summer visitors. The area is known for its beautiful lake landscapes and is part of the extensive Kymijoki waterway.",
    hints: [
      "This harbor is located in a small town in the Finnish lake district",
      "It's part of the extensive Kymijoki waterway",
      "The town and harbor share the same name",
      "It's located in Northern Savonia region",
      "The name starts with 'P' and ends with 'i'",
    ],
  },
  {
    id: 13,
    name: "Vänö",
    language: "en",
    coordinates: { lat: 59.8667, lng: 21.9167 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Traditional"],
    notableFeature: "Remote traditional island community with a small harbor",
    description:
      "Vänö is a remote island with a small year-round population maintaining traditional archipelago lifestyles. The guest harbor is small but offers basic services, and the island features beautiful nature and walking paths.",
    hints: [
      "This harbor is on a remote island with a small year-round population",
      "The island maintains traditional archipelago lifestyles",
      "It features beautiful nature and walking paths",
      "The name is very short - only 4 letters",
      "It starts with 'V' and ends with 'ö'",
    ],
  },
  {
    id: 14,
    name: "Aspö",
    language: "en",
    coordinates: { lat: 60.2833, lng: 26.4 },
    region: "Eastern Gulf of Finland",
    type: ["Guest Marina", "Fortress Island"],
    notableFeature: "Fortress island near Kotka with military history",
    description:
      "Aspö is a fortress island near Kotka with a significant military history. The guest harbor offers good services, and visitors can explore old military installations, bunkers, and beautiful coastal nature.",
    hints: [
      "This harbor is on a fortress island near Kotka",
      "The island has a significant military history",
      "Visitors can explore old military installations and bunkers",
      "The name means 'Aspen Island' in Swedish",
      "It starts with 'A' and ends with 'ö'",
    ],
  },
  {
    id: 15,
    name: "Tornio Marina",
    language: "en",
    coordinates: { lat: 65.85, lng: 24.15 },
    region: "Lapland",
    type: ["River Marina", "Border Harbor"],
    notableFeature: "Northernmost marina in the Gulf of Bothnia, on the Swedish border",
    description:
      "Located at the mouth of the Tornio River on the border with Sweden, this marina is one of the northernmost in the Gulf of Bothnia. It serves as a gateway between Finland and Sweden and offers services for boaters exploring the northern Baltic.",
    hints: [
      "This marina is located at the mouth of a river on the border with Sweden",
      "It's one of the northernmost marinas in the Gulf of Bothnia",
      "The city is known for its border twin city with Sweden",
      "The river and city share the same name",
      "The name starts with 'T'",
    ],
  },
  {
    id: 16,
    name: "Helsinki South Harbor",
    language: "en",
    coordinates: { lat: 60.1674, lng: 24.9525 },
    region: "Helsinki Metropolitan Area",
    type: ["Commercial Port", "Passenger Terminal"],
    notableFeature: "Finland's busiest passenger port in the heart of Helsinki",
    description:
      "Helsinki South Harbor (Eteläsatama) is the main passenger port in the heart of Helsinki, serving ferries to Stockholm, Tallinn, and St. Petersburg. Located next to the Market Square, it's surrounded by Helsinki's iconic landmarks including the Presidential Palace and Helsinki Cathedral.",
    hints: [
      "This harbor is located in Finland's capital city",
      "It's a major passenger port with ferries to neighboring countries",
      "It's located next to a famous market square",
      "The harbor is surrounded by iconic landmarks including a white cathedral",
      "The city name starts with 'H'",
    ],
  },
  {
    id: 17,
    name: "Turku Harbor",
    language: "en",
    coordinates: { lat: 60.4358, lng: 22.2242 },
    region: "Southwest Finland",
    type: ["Commercial Port", "Passenger Terminal", "Historical"],
    notableFeature: "Finland's oldest port with major ferry connections to Sweden",
    description:
      "Turku Harbor is Finland's oldest port with a history dating back to the 13th century. Today it's a major commercial port and passenger terminal with regular ferry connections to Stockholm. The harbor is located near Turku Castle and the mouth of the Aura River.",
    hints: [
      "This harbor is in Finland's oldest city",
      "It has major ferry connections to Stockholm",
      "It's located near a medieval castle",
      "The city was once the capital of Finland",
      "The city name starts with 'T' and has 5 letters",
    ],
  },
  {
    id: 18,
    name: "Kotka Harbor",
    language: "en",
    coordinates: { lat: 60.4665, lng: 26.9456 },
    region: "Kymenlaakso",
    type: ["Commercial Port", "Industrial Harbor"],
    notableFeature: "Major export port with a strong maritime heritage",
    description:
      "Kotka Harbor is one of Finland's major export ports, specializing in forest industry products. The city has a strong maritime heritage, reflected in its Maritime Museum and Maritime Centre Vellamo. The harbor consists of several port areas including Mussalo, Hietanen, and Kantasatama.",
    hints: [
      "This harbor is one of Finland's major export ports",
      "The city has a famous Maritime Museum",
      "It specializes in forest industry products",
      "It's located in southeastern Finland",
      "The city name starts with 'K' and has 5 letters",
    ],
  },
  {
    id: 19,
    name: "Hanko West Harbor",
    language: "en",
    coordinates: { lat: 59.8214, lng: 22.9086 },
    region: "Uusimaa",
    type: ["Guest Marina", "Commercial Port"],
    notableFeature: "Finland's southernmost mainland port with a popular beach resort",
    description:
      "Hanko West Harbor is located in Finland's southernmost mainland city, known for its beautiful sandy beaches and historic wooden villas. The harbor serves both commercial shipping and recreational boaters, with excellent facilities for visiting yachts.",
    hints: [
      "This harbor is in Finland's southernmost mainland city",
      "The city is known for its beautiful sandy beaches",
      "It has historic wooden villas from the late 19th century",
      "It was the site of a major passenger port for emigrants to America",
      "The city name starts with 'H' and has 5 letters",
    ],
  },
  {
    id: 20,
    name: "Oulu Harbor",
    language: "en",
    coordinates: { lat: 65.0124, lng: 25.4138 },
    region: "Northern Ostrobothnia",
    type: ["Commercial Port", "Industrial Harbor"],
    notableFeature: "Northernmost year-round commercial port in the Baltic Sea",
    description:
      "Oulu Harbor is the northernmost year-round commercial port in the Baltic Sea. Despite its northern location, the port remains operational throughout the winter thanks to icebreakers. It serves the industrial needs of northern Finland and is an important export hub.",
    hints: [
      "This harbor is the northernmost year-round commercial port in the Baltic Sea",
      "The city is a major technology hub in northern Finland",
      "The port remains operational throughout winter thanks to icebreakers",
      "It's located at the mouth of a river with the same name as the city",
      "The city name starts with 'O' and has 4 letters",
    ],
  },
  {
    id: 21,
    name: "Naantali Harbor",
    language: "en",
    coordinates: { lat: 60.4667, lng: 22.0333 },
    region: "Southwest Finland",
    type: ["Oil Terminal", "Commercial Port"],
    notableFeature: "Major oil port with Finland's largest oil refinery",
    description:
      "Naantali Harbor is home to Finland's largest oil refinery and serves as a major oil import terminal. The deep-water port also handles dry cargo and passenger traffic. The picturesque old town of Naantali with its wooden houses is located nearby.",
    hints: [
      "This harbor is home to Finland's largest oil refinery",
      "It's a major oil import terminal with a deep-water port",
      "The city is known for its picturesque old town with wooden houses",
      "It's located near Turku in Southwest Finland",
      "The city is also known for Moomin World theme park",
    ],
  },
  {
    id: 22,
    name: "Mariehamn West Harbor",
    language: "en",
    coordinates: { lat: 60.0922, lng: 19.9281 },
    region: "Åland Islands",
    type: ["Passenger Terminal", "Guest Marina"],
    notableFeature: "Main port of the autonomous Åland Islands",
    description:
      "Mariehamn West Harbor is the main port of the autonomous Åland Islands, serving passenger ferries between Finland, Sweden, and Estonia. The harbor is home to the famous museum ship Pommern and offers excellent facilities for visiting yachts.",
    hints: [
      "This harbor is the main port of an autonomous region of Finland",
      "It's home to the famous museum ship Pommern",
      "The city is the capital of an island province",
      "The region is Swedish-speaking",
      "The city name ends with 'hamn' (meaning harbor in Swedish)",
    ],
  },
  {
    id: 23,
    name: "Rauma Harbor",
    language: "en",
    coordinates: { lat: 61.1286, lng: 21.4931 },
    region: "Satakunta",
    type: ["Commercial Port", "Industrial Harbor"],
    notableFeature: "Historic port city with UNESCO World Heritage old town",
    description:
      "Rauma Harbor is a significant commercial port on Finland's west coast. The city is known for its well-preserved wooden old town, which is a UNESCO World Heritage site. The harbor specializes in paper, pulp, and container traffic.",
    hints: [
      "This harbor is in a city with a UNESCO World Heritage old town",
      "The city is known for its tradition of bobbin lace-making",
      "The port specializes in paper and pulp exports",
      "It's located on Finland's west coast",
      "The city name starts with 'R' and has 5 letters",
    ],
  },
  {
    id: 24,
    name: "Vaasa Harbor",
    language: "en",
    coordinates: { lat: 63.0833, lng: 21.6167 },
    region: "Ostrobothnia",
    type: ["Commercial Port", "Passenger Terminal"],
    notableFeature: "Important port connecting Finland to Sweden across the narrowest point of the Gulf of Bothnia",
    description:
      "Vaasa Harbor serves as an important link between Finland and Sweden, with regular ferry connections to Umeå across the narrowest point of the Gulf of Bothnia. The port handles both passenger and cargo traffic and is vital for the region's industry.",
    hints: [
      "This harbor has regular ferry connections to Umeå, Sweden",
      "It's located at the narrowest point of the Gulf of Bothnia",
      "The city is known for its high concentration of energy technology companies",
      "It's the largest city in the Ostrobothnia region",
      "The city name starts with 'V' and has 5 letters",
    ],
  },
  {
    id: 25,
    name: "Kemi Harbor",
    language: "en",
    coordinates: { lat: 65.7333, lng: 24.5667 },
    region: "Lapland",
    type: ["Industrial Harbor", "Commercial Port"],
    notableFeature: "Northernmost commercial port in Finland with a snow castle attraction",
    description:
      "Kemi Harbor is one of the northernmost commercial ports in Finland, serving the forest and mining industries of Lapland. The city is known for its annual snow castle and icebreaker cruises in the frozen Gulf of Bothnia.",
    hints: [
      "This harbor is one of the northernmost commercial ports in Finland",
      "The city is known for its annual snow castle",
      "It offers icebreaker cruises in the frozen Gulf of Bothnia",
      "It serves the forest and mining industries of Lapland",
      "The city name starts with 'K' and has 4 letters",
    ],
  },
  {
    id: 26,
    name: "Hamina Harbor",
    language: "en",
    coordinates: { lat: 60.5667, lng: 27.2 },
    region: "Kymenlaakso",
    type: ["Commercial Port", "Industrial Harbor"],
    notableFeature: "Deep-water port with a circular town plan",
    description:
      "Hamina Harbor is a deep-water port in southeastern Finland, specializing in liquid bulk, gas, and container traffic. The city is known for its unique circular town plan and star-shaped fortress from the 18th century.",
    hints: [
      "This harbor is a deep-water port in southeastern Finland",
      "The city has a unique circular town plan",
      "It features a star-shaped fortress from the 18th century",
      "The port specializes in liquid bulk and gas",
      "The city name starts with 'H' and has 6 letters",
    ],
  },
  {
    id: 27,
    name: "Porvoo Harbor",
    language: "en",
    coordinates: { lat: 60.3917, lng: 25.6667 },
    region: "Uusimaa",
    type: ["Historical Harbor", "Guest Marina"],
    notableFeature: "Picturesque harbor with historic red shore warehouses",
    description:
      "Porvoo Harbor is known for its picturesque red shore warehouses dating from the 18th and 19th centuries. The harbor is located at the mouth of the Porvoo River, leading to one of Finland's most charming old towns with colorful wooden houses.",
    hints: [
      "This harbor is known for its picturesque red shore warehouses",
      "It's located at the mouth of a river with the same name as the city",
      "The city has one of Finland's most charming old towns",
      "It's the second oldest city in Finland",
      "The city name starts with 'P' and has 6 letters",
    ],
  },
  {
    id: 28,
    name: "Savonlinna Harbor",
    language: "en",
    coordinates: { lat: 61.8667, lng: 28.8833 },
    region: "Southern Savonia",
    type: ["Inland Harbor", "Guest Marina"],
    notableFeature: "Harbor next to the medieval Olavinlinna Castle",
    description:
      "Savonlinna Harbor is located in the heart of Finland's lake district, next to the medieval Olavinlinna Castle. The harbor serves both passenger ships navigating the Saimaa lake system and recreational boaters. The city is famous for its annual opera festival.",
    hints: [
      "This harbor is located next to a medieval castle",
      "It's in the heart of Finland's lake district",
      "The city hosts a famous annual opera festival",
      "It's located on Lake Saimaa",
      "The city name means 'Castle of Savonia'",
    ],
  },
  {
    id: 29,
    name: "Lahti Harbor",
    language: "en",
    coordinates: { lat: 61.0333, lng: 25.65 },
    region: "Päijät-Häme",
    type: ["Inland Harbor", "Guest Marina"],
    notableFeature: "Major inland harbor at the southern end of Lake Päijänne",
    description:
      "Lahti Harbor is located at the southern end of Lake Päijänne, Finland's second largest lake. The harbor serves as a gateway to the lake system and offers services for both passenger ships and recreational boaters. The city is known for its winter sports traditions.",
    hints: [
      "This harbor is located at the southern end of Lake Päijänne",
      "The city is known for its winter sports traditions",
      "It hosts an annual international ski jumping competition",
      "It's a major inland harbor serving as a gateway to a lake system",
      "The city name starts with 'L' and has 5 letters",
    ],
  },
  {
    id: 30,
    name: "Kuopio Harbor",
    language: "en",
    coordinates: { lat: 62.8833, lng: 27.6833 },
    region: "Northern Savonia",
    type: ["Inland Harbor", "Guest Marina"],
    notableFeature: "Vibrant harbor in the heart of the Finnish lake district",
    description:
      "Kuopio Harbor is a vibrant inland harbor in the heart of the Finnish lake district. Located on Lake Kallavesi, part of the Saimaa lake system, it serves passenger ships and recreational boaters. The harbor area features restaurants, cafes, and a market hall.",
    hints: [
      "This harbor is located on Lake Kallavesi",
      "It's part of the Saimaa lake system",
      "The city is known for its fish market and market hall",
      "It's famous for a special local fish pastry called 'kalakukko'",
      "The city name starts with 'K' and has 6 letters",
    ],
  },
  {
    id: 31,
    name: "Sysmä Harbor",
    language: "en",
    coordinates: { lat: 61.5028, lng: 25.6856 },
    region: "Päijät-Häme",
    type: ["Inland Marina", "Guest Harbor"],
    notableFeature: "Charming harbor in the historic municipality on Lake Päijänne",
    description:
      "Sysmä Harbor is a picturesque inland marina located in the historic municipality of Sysmä on the eastern shore of Lake Päijänne. The harbor offers good services for boaters including fuel, electricity, and waste disposal. The nearby village center has restaurants, shops, and a historic church.",
    hints: [
      "This harbor is located in a historic municipality on Lake Päijänne",
      "The municipality is known for its cultural events including a music festival",
      "It's located on the eastern shore of Finland's second largest lake",
      "The harbor is near a village with a medieval stone church",
      "The name starts with 'S' and ends with 'ä'",
    ],
  },
  {
    id: 32,
    name: "Loviisa Harbor",
    language: "en",
    coordinates: { lat: 60.4569, lng: 26.2264 },
    region: "Uusimaa",
    type: ["Guest Marina", "Historical Harbor"],
    notableFeature: "Charming small town harbor with wooden old town and maritime history",
    description:
      "Loviisa Harbor serves the charming coastal town known for its well-preserved wooden old town and maritime history. The guest marina offers good services for visiting boats and is within walking distance of the town center with its cafes, restaurants, and historic sites including the Svartholm sea fortress.",
    hints: [
      "This harbor is in a coastal town known for its well-preserved wooden old town",
      "The town was named after a Swedish queen",
      "It's located about 90 km east of Helsinki",
      "The town is known for its annual historical events and maritime festivals",
      "The name starts with 'L' and has 7 letters",
    ],
  },
  {
    id: 33,
    name: "Tammisaari Harbor",
    language: "en",
    coordinates: { lat: 59.9758, lng: 23.4364 },
    region: "Uusimaa",
    type: ["Guest Marina", "Archipelago Gateway"],
    notableFeature: "Historic harbor town serving as a gateway to the western Uusimaa archipelago",
    description:
      "Tammisaari (Ekenäs in Swedish) Harbor is located in a picturesque bilingual town that serves as a gateway to the western Uusimaa archipelago. The guest marina is situated right next to the charming old town with wooden houses, restaurants, and boutiques. The area is part of the Ekenäs Archipelago National Park.",
    hints: [
      "This harbor is in a bilingual town that serves as a gateway to an archipelago",
      "The town is known for its well-preserved wooden old town",
      "It's part of the city of Raseborg formed in 2009",
      "It's located near a national park named after the town",
      "The Finnish name starts with 'T', but it's also known by its Swedish name 'Ekenäs'",
    ],
  },
  {
    id: 34,
    name: "Uusikaupunki Harbor",
    language: "en",
    coordinates: { lat: 60.8, lng: 21.4167 },
    region: "Southwest Finland",
    type: ["Guest Marina", "Commercial Port"],
    notableFeature: "Historic shipbuilding town with a well-preserved wooden old town",
    description:
      "Uusikaupunki (Nystad in Swedish) Harbor serves both recreational boaters and commercial shipping. The town is known for its shipbuilding tradition, car manufacturing, and well-preserved wooden old town. The guest marina offers good services and is located near the town center with its maritime museum and restaurants.",
    hints: [
      "This harbor is in a historic shipbuilding town in Southwest Finland",
      "The town is now known for car manufacturing",
      "It has a well-preserved wooden old town",
      "The town's name literally means 'New Town' in Finnish",
      "The Peace Treaty ending the Great Northern War was signed here in 1721",
    ],
  },
  {
    id: 35,
    name: "Kristiinankaupunki Harbor",
    language: "en",
    coordinates: { lat: 62.2736, lng: 21.3758 },
    region: "Ostrobothnia",
    type: ["Guest Marina", "Historical Harbor"],
    notableFeature: "Well-preserved wooden town with a rich maritime trading history",
    description:
      "Kristiinankaupunki (Kristinestad in Swedish) Harbor serves a charming coastal town with one of the best-preserved wooden town centers in Finland. Founded in 1649, the town has a rich maritime trading history. The guest marina offers good services and is located near the historic town center with its wooden houses, narrow streets, and maritime atmosphere.",
    hints: [
      "This harbor is in one of the best-preserved wooden towns in Finland",
      "The town was founded in 1649 and named after Queen Christina of Sweden",
      "It's located in Ostrobothnia on the west coast",
      "The town is officially bilingual with a significant Swedish-speaking population",
      "The Finnish name is quite long (17 letters) and starts with 'K'",
    ],
  },
  {
    id: 36,
    name: "Kaskinen Harbor",
    language: "en",
    coordinates: { lat: 62.3833, lng: 21.2167 },
    region: "Ostrobothnia",
    type: ["Commercial Port", "Guest Marina"],
    notableFeature: "Finland's smallest town by area, located entirely on an island",
    description:
      "Kaskinen (Kaskö in Swedish) Harbor serves Finland's smallest town by area, located entirely on an island. The town has a strong maritime and industrial heritage, with a deep-water commercial port and a small guest marina. The compact town center with its grid plan and wooden houses is within walking distance of the marina.",
    hints: [
      "This harbor is in Finland's smallest town by area",
      "The town is located entirely on an island",
      "It has a deep-water commercial port and a small guest marina",
      "The town has a strong Swedish-speaking heritage",
      "The name starts with 'K' and means 'little chest' in Finnish",
    ],
  },
  {
    id: 37,
    name: "Mikkeli Harbor",
    language: "en",
    coordinates: { lat: 61.6875, lng: 27.2736 },
    region: "Southern Savonia",
    type: ["Inland Harbor", "Lake Marina"],
    notableFeature: "Regional capital's harbor on Lake Saimaa with historical significance",
    description:
      "Mikkeli Harbor serves the regional capital of Southern Savonia, located on a bay of Lake Saimaa. The city has historical significance as the headquarters of the Finnish Army during WWII. The harbor offers services for recreational boaters exploring the Saimaa lake system and is connected to the city center with its restaurants, shops, and cultural attractions.",
    hints: [
      "This harbor serves a regional capital located on Lake Saimaa",
      "The city was the headquarters of the Finnish Army during WWII",
      "It's located in the Southern Savonia region",
      "The city hosts a major annual ballet festival",
      "The name starts with 'M' and has 7 letters",
    ],
  },
  {
    id: 38,
    name: "Joensuu Harbor",
    language: "en",
    coordinates: { lat: 62.6, lng: 29.7667 },
    region: "North Karelia",
    type: ["Inland Harbor", "River Harbor"],
    notableFeature: "University city's harbor at the mouth of the Pielisjoki River on Lake Pyhäselkä",
    description:
      "Joensuu Harbor is located at the mouth of the Pielisjoki River where it flows into Lake Pyhäselkä, part of the Saimaa lake system. The city is the regional capital of North Karelia and a university city. The harbor serves recreational boaters and is located near the city center with its market square, pedestrian streets, and cultural attractions.",
    hints: [
      "This harbor is located at the mouth of the Pielisjoki River",
      "The city is the regional capital of North Karelia",
      "It's a university city with a lively cultural scene",
      "The harbor is part of the Saimaa lake system",
      "The name means 'mouth of the river' in Finnish",
    ],
  },
  {
    id: 39,
    name: "Jyväskylä Harbor",
    language: "en",
    coordinates: { lat: 62.2333, lng: 25.7333 },
    region: "Central Finland",
    type: ["Inland Harbor", "Lake Marina"],
    notableFeature: "University city's harbor at the northern end of Lake Päijänne",
    description:
      "Jyväskylä Harbor is located at the northern end of Lake Päijänne in Central Finland. The city is known for its university, Alvar Aalto architecture, and as the 'Athens of Finland' due to its educational significance. The harbor serves recreational boaters exploring Lake Päijänne and is near the city center with its restaurants, shops, and cultural attractions.",
    hints: [
      "This harbor is located at the northern end of Lake Päijänne",
      "The city is known as the 'Athens of Finland' due to its educational significance",
      "It's famous for architecture designed by Alvar Aalto",
      "The city hosts an annual rally competition",
      "The name starts with 'J' and ends with 'ä'",
    ],
  },
  {
    id: 40,
    name: "Hämeenlinna Harbor",
    language: "en",
    coordinates: { lat: 61.0, lng: 24.4667 },
    region: "Tavastia Proper",
    type: ["Inland Harbor", "Lake Marina"],
    notableFeature: "Historic city's harbor on Lake Vanajavesi near a medieval castle",
    description:
      "Hämeenlinna Harbor is located on Lake Vanajavesi in one of Finland's oldest inland cities. The city is known for its medieval castle, Häme Castle, and as the birthplace of composer Jean Sibelius. The harbor serves recreational boaters and is connected to the city center with its restaurants, shops, and cultural attractions.",
    hints: [
      "This harbor is located on Lake Vanajavesi in one of Finland's oldest inland cities",
      "The city is known for its medieval castle",
      "It's the birthplace of composer Jean Sibelius",
      "The city name literally means 'Tavastia Castle' in Finnish",
      "The name starts with 'H' and ends with 'a'",
    ],
  },
  {
    id: 41,
    name: "Tampere Harbor",
    language: "en",
    coordinates: { lat: 61.5, lng: 23.7667 },
    region: "Pirkanmaa",
    type: ["Inland Harbor", "Lake Marina"],
    notableFeature: "Industrial city's harbor on Lake Pyhäjärvi with restored factory buildings",
    description:
      "Tampere Harbor (Laukontori) is located on Lake Pyhäjärvi in Finland's largest inland city. Known as the 'Manchester of Finland' due to its industrial heritage, the city is built between two lakes connected by the Tammerkoski rapids. The harbor area features restored factory buildings, restaurants, and is near the city center with its shops and cultural attractions.",
    hints: [
      "This harbor is located on Lake Pyhäjärvi in Finland's largest inland city",
      "The city is known as the 'Manchester of Finland' due to its industrial heritage",
      "It's built between two lakes connected by rapids",
      "The harbor area features restored factory buildings",
      "The city name starts with 'T' and has 7 letters",
    ],
  },
  {
    id: 42,
    name: "Raahe Harbor",
    language: "en",
    coordinates: { lat: 64.6833, lng: 24.4833 },
    region: "Northern Ostrobothnia",
    type: ["Commercial Port", "Guest Marina"],
    notableFeature: "Historic coastal town with a well-preserved wooden old town and industrial port",
    description:
      "Raahe Harbor serves both industrial shipping and recreational boating. The town has a well-preserved wooden old town, Pekkatori, and a strong maritime heritage showcased in its maritime museum. The guest marina offers services for visiting boaters and is within walking distance of the town center.",
    hints: [
      "This harbor serves a historic coastal town with a well-preserved wooden old town",
      "The town has a strong maritime heritage and a maritime museum",
      "It has both an industrial port and a guest marina",
      "It's located in Northern Ostrobothnia on the Gulf of Bothnia",
      "The name starts with 'R' and has 5 letters",
    ],
  },
  {
    id: 43,
    name: "Kokkola Harbor",
    language: "en",
    coordinates: { lat: 63.8383, lng: 23.1317 },
    region: "Central Ostrobothnia",
    type: ["Commercial Port", "Guest Marina"],
    notableFeature: "Important export port with a well-preserved wooden old town",
    description:
      "Kokkola Harbor (Karleby in Swedish) is an important export port on the Gulf of Bothnia. The city has a well-preserved wooden old town, Neristan, and a strong maritime and trading heritage. The guest marina offers services for visiting boaters and is near the city center with its shops, restaurants, and cultural attractions.",
    hints: [
      "This harbor is an important export port on the Gulf of Bothnia",
      "The city has a well-preserved wooden old town called Neristan",
      "It's the capital of the Central Ostrobothnia region",
      "The city is officially bilingual with both Finnish and Swedish names",
      "The Finnish name starts with 'K' and has 7 letters",
    ],
  },
  {
    id: 44,
    name: "Pietarsaari Harbor",
    language: "en",
    coordinates: { lat: 63.6667, lng: 22.7 },
    region: "Ostrobothnia",
    type: ["Commercial Port", "Guest Marina"],
    notableFeature: "Bilingual coastal city with a strong maritime and shipbuilding tradition",
    description:
      "Pietarsaari Harbor (Jakobstad in Swedish) serves a bilingual coastal city with a strong maritime and shipbuilding tradition. The guest marina offers good services for visiting boaters and is near the city center with its shops, restaurants, and attractions including the botanical garden Skata and the Nanoq Arctic Museum.",
    hints: [
      "This harbor serves a bilingual coastal city with a strong maritime tradition",
      "The city has a Swedish-speaking majority and a Finnish-speaking minority",
      "It features a botanical garden called Skata and the Nanoq Arctic Museum",
      "The city was named after Jacob De la Gardie in the 17th century",
      "The Finnish name starts with 'P', but it's better known internationally by its Swedish name 'Jakobstad'",
    ],
  },
  {
    id: 45,
    name: "Uusikaarlepyy Harbor",
    language: "en",
    coordinates: { lat: 63.5222, lng: 22.5303 },
    region: "Ostrobothnia",
    type: ["River Harbor", "Guest Marina"],
    notableFeature: "Small bilingual city at the mouth of the Lapuanjoki River",
    description:
      "Uusikaarlepyy Harbor (Nykarleby in Swedish) is located at the mouth of the Lapuanjoki River. This small, predominantly Swedish-speaking city has a charming center with wooden buildings and a rich cultural heritage. The small guest marina offers basic services for visiting boaters.",
    hints: [
      "This harbor is located at the mouth of the Lapuanjoki River",
      "The city is predominantly Swedish-speaking",
      "It's one of the smallest cities in Finland",
      "The poet Zacharias Topelius was born here",
      "The Finnish name is quite long and starts with 'U', but it's also known by its Swedish name 'Nykarleby'",
    ],
  },
  {
    id: 46,
    name: "Kalajoki Harbor",
    language: "en",
    coordinates: { lat: 64.2567, lng: 23.9486 },
    region: "Northern Ostrobothnia",
    type: ["Guest Marina", "Beach Resort"],
    notableFeature: "Popular tourist destination with extensive sandy beaches",
    description:
      "Kalajoki Harbor serves a popular coastal tourist destination known for its extensive sandy beaches, sand dunes, and holiday resorts. The guest marina offers good services for visiting boaters and is located near the beach area with its restaurants, activities, and accommodation options.",
    hints: [
      "This harbor serves a popular coastal tourist destination known for sandy beaches",
      "The area features unusual sand dunes for Finland",
      "It's a popular summer holiday resort",
      "It's located in Northern Ostrobothnia on the Gulf of Bothnia",
      "The name starts with 'K' and means 'fish river' in Finnish",
    ],
  },
  {
    id: 47,
    name: "Lappeenranta Harbor",
    language: "en",
    coordinates: { lat: 61.0681, lng: 28.1889 },
    region: "South Karelia",
    type: ["Inland Harbor", "Canal Gateway"],
    notableFeature: "Vibrant harbor area near a fortress, gateway to the Saimaa Canal",
    description:
      "Lappeenranta Harbor is a vibrant inland harbor on Lake Saimaa, serving as a gateway to the Saimaa Canal that connects to Russia. The city features a historic fortress and a lively harbor area with restaurants, cruise ships, and a market. The marina offers good services for recreational boaters exploring the Saimaa lake system.",
    hints: [
      "This harbor is on Lake Saimaa and serves as a gateway to a canal connecting to Russia",
      "The city features a historic fortress overlooking the harbor",
      "It has a vibrant harbor area with restaurants and a market",
      "The city is known for its technical university",
      "The name ends with 'ranta' meaning 'shore' in Finnish",
    ],
  },
  {
    id: 48,
    name: "Imatra Harbor",
    language: "en",
    coordinates: { lat: 61.1722, lng: 28.7756 },
    region: "South Karelia",
    type: ["Inland Harbor", "River Harbor"],
    notableFeature: "Harbor near the powerful Imatrankoski Rapids on the Russian border",
    description:
      "Imatra Harbor is located on Lake Saimaa near the powerful Imatrankoski Rapids and close to the Russian border. The city developed around a hydroelectric power plant and has a unique industrial heritage. The marina serves recreational boaters exploring the eastern parts of the Saimaa lake system.",
    hints: [
      "This harbor is on Lake Saimaa near powerful rapids",
      "The city is very close to the Russian border",
      "It developed around a hydroelectric power plant",
      "The rapids are a famous natural attraction that have inspired artists",
      "The name starts with 'I' and has 6 letters",
    ],
  },
  {
    id: 49,
    name: "Kemi-Tornio Harbor",
    language: "en",
    coordinates: { lat: 65.7361, lng: 24.5653 },
    region: "Lapland",
    type: ["Commercial Port", "Industrial Harbor"],
    notableFeature: "Major industrial port serving the forest and mining industries of Lapland",
    description:
      "Kemi-Tornio Harbor is a major industrial port complex serving the forest and mining industries of Lapland. The area is known for its pulp and paper mills, steel production, and as a logistics hub for northern Finland. The port handles bulk cargo, containers, and industrial products.",
    hints: [
      "This harbor is a major industrial port complex in Lapland",
      "It serves the forest and mining industries of northern Finland",
      "The area is known for pulp and paper mills and steel production",
      "It's named after two neighboring cities",
      "One of the cities is known for its annual snow castle",
    ],
  },
  {
    id: 50,
    name: "Rovaniemi Harbor",
    language: "en",
    coordinates: { lat: 66.5, lng: 25.7167 },
    region: "Lapland",
    type: ["River Harbor", "Arctic Harbor"],
    notableFeature: "Harbor in the 'official hometown of Santa Claus' at the Arctic Circle",
    description:
      "Rovaniemi Harbor is located on the Kemijoki River in the capital of Finnish Lapland, known as the 'official hometown of Santa Claus.' The city is situated at the Arctic Circle and serves as a gateway to the northern wilderness. The small harbor serves river boats and is near the city center with its shops, restaurants, and attractions including the Arktikum museum.",
    hints: [
      "This harbor is located on the Kemijoki River in the capital of Finnish Lapland",
      "The city is known as the 'official hometown of Santa Claus'",
      "It's situated at the Arctic Circle",
      "The city was almost completely rebuilt after WWII",
      "The name starts with 'R' and has 9 letters",
    ],
  },
  {
    id: 51,
    name: "Parainen Harbor",
    language: "en",
    coordinates: { lat: 60.3, lng: 22.3 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Industrial Harbor"],
    notableFeature: "Gateway to the Archipelago Trail with limestone industry heritage",
    description:
      "Parainen (Pargas in Swedish) Harbor serves as a gateway to the Archipelago Trail, a popular route connecting the islands of the Archipelago Sea. The town has a strong limestone industry heritage with a large quarry and cement factory. The guest marina offers good services for boaters and is near the town center with its shops and restaurants.",
    hints: [
      "This harbor serves as a gateway to the Archipelago Trail",
      "The town has a strong limestone industry heritage with a large quarry",
      "It's a bilingual municipality with both Finnish and Swedish names",
      "It's the starting point for exploring the Archipelago Sea by car and ferry",
      "The Finnish name starts with 'P', the Swedish name is 'Pargas'",
    ],
  },
  {
    id: 52,
    name: "Korppoo Harbor",
    language: "en",
    coordinates: { lat: 60.1667, lng: 21.5833 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Ferry Harbor"],
    notableFeature: "Important stop on the Archipelago Trail with historic wooden church",
    description:
      "Korppoo (Korpo in Swedish) Harbor is an important stop on the Archipelago Trail, serving both recreational boaters and car ferries. The island features a historic wooden church from the 15th century and a traditional archipelago village. The guest marina offers good services and is near the village center with its small shops and restaurants.",
    hints: [
      "This harbor is an important stop on the Archipelago Trail",
      "The island features a historic wooden church from the 15th century",
      "It's a bilingual municipality with both Finnish and Swedish names",
      "It's part of the city of Pargas/Parainen since 2009",
      "The Finnish name starts with 'K', the Swedish name is 'Korpo'",
    ],
  },
  {
    id: 53,
    name: "Nauvo Harbor",
    language: "en",
    coordinates: { lat: 60.1917, lng: 21.9083 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Archipelago Hub"],
    notableFeature: "Popular archipelago hub with a vibrant guest harbor and historic church",
    description:
      "Nauvo (Nagu in Swedish) Harbor is one of the most popular guest harbors in the Archipelago Sea, serving as a hub for boaters exploring the area. The island features a medieval stone church and a vibrant village center. The guest harbor offers excellent services and is surrounded by restaurants, cafes, and shops, creating a lively maritime atmosphere during summer.",
    hints: [
      "This harbor is one of the most popular guest harbors in the Archipelago Sea",
      "The island features a medieval stone church",
      "It has a vibrant village center with restaurants and shops",
      "It's a bilingual municipality with both Finnish and Swedish names",
      "The Finnish name starts with 'N', the Swedish name is 'Nagu'",
    ],
  },
  {
    id: 54,
    name: "Houtskär Harbor",
    language: "en",
    coordinates: { lat: 60.2167, lng: 21.3667 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Traditional"],
    notableFeature: "Remote archipelago island with traditional wooden houses and church",
    description:
      "Houtskär (Houtskari in Finnish) Harbor serves a remote island in the outer Archipelago Sea. The island features traditional wooden houses, a wooden church from the 18th century, and beautiful archipelago landscapes. The guest marina offers basic services for visiting boaters and is near the small village center.",
    hints: [
      "This harbor serves a remote island in the outer Archipelago Sea",
      "The island features traditional wooden houses and a wooden church",
      "It's a predominantly Swedish-speaking area",
      "It's part of the city of Pargas/Parainen since 2009",
      "The Swedish name starts with 'H', the Finnish name is 'Houtskari'",
    ],
  },
  {
    id: 55,
    name: "Iniö Harbor",
    language: "en",
    coordinates: { lat: 60.4, lng: 21.4167 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Remote Island"],
    notableFeature: "Finland's smallest former municipality with traditional archipelago culture",
    description:
      "Iniö Harbor serves one of the most remote inhabited island groups in the Archipelago Sea. Formerly Finland's smallest municipality, the area maintains a strong traditional archipelago culture. The guest marina offers basic services for visiting boaters and is near the small village center with its church and local services.",
    hints: [
      "This harbor serves one of the most remote inhabited island groups in the Archipelago Sea",
      "It was formerly Finland's smallest municipality",
      "The area maintains a strong traditional archipelago culture",
      "It's part of the city of Pargas/Parainen since 2009",
      "The name is the same in both Finnish and Swedish",
    ],
  },
  {
    id: 56,
    name: "Kasnäs Harbor",
    language: "en",
    coordinates: { lat: 59.9167, lng: 22.4167 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Nature Tourism"],
    notableFeature: "Modern marina near the Archipelago National Park visitor center",
    description:
      "Kasnäs Harbor is a modern marina located at the tip of the Kemiönsaari peninsula, serving as a gateway to the Archipelago National Park. The area features the Blue Mussel visitor center, a spa hotel, and excellent facilities for boaters. The harbor is a popular starting point for exploring the southern parts of the Archipelago Sea.",
    hints: [
      "This harbor is located at the tip of the Kemiönsaari peninsula",
      "It serves as a gateway to the Archipelago National Park",
      "The area features the Blue Mussel visitor center",
      "It has a spa hotel and excellent facilities for boaters",
      "The name starts with 'K' and ends with 's'",
    ],
  },
  {
    id: 57,
    name: "Kustavi Harbor",
    language: "en",
    coordinates: { lat: 60.55, lng: 21.3667 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Fishing Village"],
    notableFeature: "Historic fishing village at the northern edge of the Archipelago Sea",
    description:
      "Kustavi Harbor serves a historic fishing village at the northern edge of the Archipelago Sea. The area has a strong maritime heritage and is known for its traditional fish smoking. The guest marina offers good services for visiting boaters and is near the village center with its restaurants specializing in local fish dishes.",
    hints: [
      "This harbor serves a historic fishing village at the northern edge of the Archipelago Sea",
      "The area has a strong maritime heritage and is known for traditional fish smoking",
      "It's a popular summer destination with many vacation homes",
      "The municipality has more islands than mainland",
      "The name starts with 'K' and has 7 letters",
    ],
  },
  {
    id: 58,
    name: "Rymättylä Harbor",
    language: "en",
    coordinates: { lat: 60.3833, lng: 21.9333 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Fishing Village"],
    notableFeature: "Traditional fishing village with medieval stone church",
    description:
      "Rymättylä Harbor serves a traditional fishing village on the island of the same name. The area has a strong fishing heritage and features a medieval stone church from the 15th century. The guest marina offers services for visiting boaters and is near the village center with its small shops and restaurants.",
    hints: [
      "This harbor serves a traditional fishing village on an island",
      "The area has a strong fishing heritage",
      "It features a medieval stone church from the 15th century",
      "It's now part of the city of Naantali",
      "The name starts with 'R' and ends with 'ä'",
    ],
  },
  {
    id: 59,
    name: "Velkua Harbor",
    language: "en",
    coordinates: { lat: 60.45, lng: 21.6833 },
    region: "Archipelago Sea",
    type: ["Guest Marina", "Island Community"],
    notableFeature: "Idyllic island community with wooden church and traditional landscapes",
    description:
      "Velkua Harbor serves an idyllic island community consisting of several inhabited islands. The area features a wooden church from the 18th century and traditional archipelago landscapes. The small guest marina offers basic services for visiting boaters and is near the main village with its local services.",
    hints: [
      "This harbor serves an idyllic island community consisting of several inhabited islands",
      "The area features a wooden church from the 18th century",
      "It was formerly one of Finland's smallest municipalities",
      "It's now part of the city of Naantali",
      "The name starts with 'V' and has 6 letters",
    ],
  },
  {
    id: 60,
    name: "Merikarvia Harbor",
    language: "en",
    coordinates: { lat: 61.8583, lng: 21.4917 },
    region: "Satakunta",
    type: ["Fishing Harbor", "Guest Marina"],
    notableFeature: "Traditional fishing town with wooden boathouses and strong maritime heritage",
    description:
      "Merikarvia Harbor serves a traditional fishing town on the coast of the Bothnian Sea. The area is known for its wooden boathouses, strong fishing tradition, and river famous for salmon fishing. The guest marina offers services for visiting boaters and is near the town center with its wooden church and local services.",
    hints: [
      "This harbor serves a traditional fishing town on the coast of the Bothnian Sea",
      "The area is known for its wooden boathouses and strong fishing tradition",
      "It has a river famous for salmon fishing",
      "The town name literally means 'sea reef' in Finnish",
      "The name starts with 'M' and has 10 letters",
    ],
  },
]


// Function to fetch harbor data
export async function fetchHarborData(language = "en") {
  // In a real app, this would be an API call
  return new Promise((resolve) => {
    // Simulate network delay
    setTimeout(() => {
      resolve(harbors)
    }, 800)
  })
}


