// Finnish harbors and marinas database - Finnish version
// Comprehensive collection of coastal and inland harbors across Finland

export const harbors = [
  {
    id: 1,
    name: "Elisaari",
    language: "fi",
    coordinates: { lat: 60.0167, lng: 23.9333 },
    region: "Länsi-Uusimaa",
    type: ["Vierasvenesatama", "Luontosatama"],
    notableFeature: "Kaunis saari, jossa ravintola ja luontopolkuja",
    description:
      "Elisaari on suosittu vierasvenesatama Uudenmaan läntisessä saaristossa. Saari tarjoaa kauniita luontopolkuja, ravintolan ja saunatilat vierailijoille. Se on rauhallinen kohde, joka on hyvin suojattu tuulilta.",
    hints: [
      "Tämä satama sijaitsee saarella Länsi-Uudellamaalla",
      "Saarella on ravintola ja luontopolkuja",
      "Se on suosittu kohde perheiden veneilymatkoille",
      "Nimi alkaa kirjaimella 'E'",
      "Se sijaitsee lähellä Inkoota",
    ],
  },
  {
    id: 2,
    name: "Örö",
    language: "fi",
    coordinates: { lat: 59.8089, lng: 22.3347 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Historiallinen"],
    notableFeature: "Entinen sotilassaari, jossa ainutlaatuinen luonto ja historiallisia linnoituksia",
    description:
      "Örö on kiehtova entinen sotilassaari ulkosaaristossa, joka avattiin yleisölle vuonna 2015. Siellä on harvinaista kasvillisuutta, historiallisia rannikkotykistön linnoituksia ja vierasvenesatama nykyaikaisilla palveluilla.",
    hints: [
      "Tämä satama sijaitsee entisellä sotilassaarella",
      "Se sijaitsee Saaristomeren kansallispuistossa",
      "Saarella on harvinaista kasvillisuutta ja rannikkotykistön linnoituksia",
      "Nimi on hyvin lyhyt",
      "Se alkaa kirjaimella 'Ö'",
    ],
  },
  {
    id: 3,
    name: "Jurmo",
    language: "fi",
    coordinates: { lat: 59.8272, lng: 21.5772 },
    region: "Ulkosaaristomeri",
    type: ["Vierasvenesatama", "Perinteinen"],
    notableFeature: "Syrjäinen saari, jossa ainutlaatuinen geologia ja perinteinen saaristokylä",
    description:
      "Jurmo on syrjäinen, karu saari ulkosaaristossa, jossa on jääkauden jäätiköiden muovaama erityinen maisema. Siellä on pieni perinteinen kylä, vierasvenesatama ja se tunnetaan ainutlaatuisesta luonnostaan ja lintubongausmahdollisuuksistaan.",
    hints: [
      "Tämä satama sijaitsee syrjäisellä, karulla saarella ulkosaaristossa",
      "Saarella on jääkauden jäätiköiden muovaama erityinen maisema",
      "Se tunnetaan lintubongauksesta ja ainutlaatuisesta luonnosta",
      "Saarella on pieni perinteinen kylä",
      "Nimi rimmaa sanan 'Turmo' kanssa",
    ],
  },
  {
    id: 4,
    name: "Päijänne Marina",
    language: "fi",
    coordinates: { lat: 61.6167, lng: 25.5667 },
    region: "Päijänne",
    type: ["Sisävesisatama", "Järvisatama"],
    notableFeature: "Suuri venesatama Suomen toiseksi suurimmalla järvellä",
    description:
      "Päijänteen rannalla sijaitseva satama toimii keskuksena sisävesien veneilijöille, jotka tutkivat Suomen toiseksi suurinta järveä. Se tarjoaa kattavat palvelut, mukaan lukien polttoaineen, huollon ja ravintolan.",
    hints: [
      "Tämä satama sijaitsee Suomen toiseksi suurimmalla järvellä",
      "Se on suosittu lähtöpiste läheisen kansallispuiston tutkimiseen",
      "Järvi jakaa nimensä sataman kanssa",
      "Se sijaitsee Keski-Suomessa",
      "Nimi alkaa kirjaimella 'P'",
    ],
  },
  {
    id: 5,
    name: "Seili",
    language: "fi",
    coordinates: { lat: 60.2361, lng: 21.9444 },
    region: "Sisäsaaristomeri",
    type: ["Vierasvenesatama", "Historiallinen"],
    notableFeature: "Entinen leprasairaala, jossa puukirkko ja tutkimusasema",
    description:
      "Seilillä (ruotsiksi Själö) on synkkä historia entisenä leprasiirtolana ja mielisairaalasaarena. Nykyään siellä toimii biologinen tutkimusasema ja vierasvenesatama vierailijoille. Puukirkko ja vanhat sairaalarakennukset kertovat saaren kiehtovasta historiasta.",
    hints: [
      "Tämä satama sijaitsee saarella, jolla on synkkä historia entisenä leprasiirtolana",
      "Nykyään siellä toimii biologinen tutkimusasema",
      "Siellä on puukirkko ja vanhoja sairaalarakennuksia",
      "Saaren nimi on erilainen suomeksi ja ruotsiksi",
      "Suomeksi se alkaa kirjaimella 'S' ja siinä on 5 kirjainta",
    ],
  },
  {
    id: 6,
    name: "Utö",
    language: "fi",
    coordinates: { lat: 59.7833, lng: 21.3667 },
    region: "Ulkosaaristomeri",
    type: ["Vierasvenesatama", "Majakkasaari"],
    notableFeature: "Suomen eteläisin ympärivuotisesti asuttu saari, jossa historiallinen majakka",
    description:
      "Utö on Suomen eteläisin ympärivuotisesti asuttu saari, jossa on historiallinen majakka, pieni kylä ja vierasvenesatama. Saarella on rikas merenkulkuhistoria ja se tarjoaa näkymän ulkosaariston aitoon elämään.",
    hints: [
      "Tämä satama sijaitsee Suomen eteläisimmällä ympärivuotisesti asutulla saarella",
      "Saarella on historiallinen majakka",
      "Sillä on rikas merenkulkuhistoria ja pieni kylä",
      "Nimi on hyvin lyhyt - vain kolme kirjainta",
      "Se alkaa kirjaimella 'U'",
    ],
  },
  {
    id: 7,
    name: "Saimaa Harbor",
    language: "fi",
    coordinates: { lat: 61.8667, lng: 28.8833 },
    region: "Saimaa",
    type: ["Sisävesisatama", "Järvisatama"],
    notableFeature: "Satama Suomen suurimmalla järvellä, jossa elää uhanalainen saimaannorppa",
    description:
      "Tämä satama sijaitsee Saimaalla, Suomen suurimmalla järvellä, jossa elää uhanalainen saimaannorppa. Satama tarjoaa palveluja veneilijöille, jotka tutkivat laajaa Saimaan järvialuetta tuhansine saarineen.",
    hints: [
      "Tämä satama sijaitsee Suomen suurimmalla järvellä",
      "Järvellä elää uhanalainen makean veden hylje",
      "Järvialueella on tuhansia saaria ja luotoja",
      "Se sijaitsee Itä-Suomessa",
      "Nimi alkaa kirjaimella 'S'",
    ],
  },
  {
    id: 8,
    name: "Kökar",
    language: "fi",
    coordinates: { lat: 59.9167, lng: 20.9 },
    region: "Ahvenanmaan saaristo",
    type: ["Vierasvenesatama", "Kulttuurikohde"],
    notableFeature: "Syrjäinen Ahvenanmaan saari, jossa keskiaikaisen luostarin rauniot",
    description:
      "Kökar on yksi Ahvenanmaan saariston syrjäisimmistä asutuista saarista. Siellä on keskiaikaisen fransiskaaniluostarin rauniot, kaunis kirkko ja useita vierasvenesatamia. Saarella on rikas kalastusperinne ja ainutlaatuisia kulttuuriperinteitä.",
    hints: [
      "Tämä satama sijaitsee yhdellä Ahvenanmaan saariston syrjäisimmistä asutuista saarista",
      "Saarella on keskiaikaisen fransiskaaniluostarin rauniot",
      "Sillä on rikas kalastusperinne ja ainutlaatuisia kulttuuriperinteitä",
      "Nimi on viisi kirjainta pitkä",
      "Se alkaa kirjaimella 'K' ja siinä on 'ö'",
    ],
  },
  {
    id: 9,
    name: "Inari Marina",
    language: "fi",
    coordinates: { lat: 68.9, lng: 27.0333 },
    region: "Lappi",
    type: ["Sisävesisatama", "Arktinen satama"],
    notableFeature: "Pohjoisin merkittävä venesatama Suomessa, Inarijärvellä",
    description:
      "Inarijärven rannalla Suomen Lapissa sijaitseva satama on yksi Suomen pohjoisimmista venesatamista. Se toimii tukikohtana Pohjois-Lapin erämaa-alueiden tutkimiseen ja alkuperäiskansan saamelaisten pyhien paikkojen vierailuun.",
    hints: [
      "Tämä satama on yksi Suomen pohjoisimmista",
      "Se sijaitsee suurella järvellä Lapissa",
      "Järvi ja satama jakavat saman nimen",
      "Se on lähellä alkuperäiskansan saamelaisten pyhiä paikkoja",
      "Nimi alkaa kirjaimella 'I'",
    ],
  },
  {
    id: 10,
    name: "Jussarö",
    language: "fi",
    coordinates: { lat: 59.8333, lng: 23.5667 },
    region: "Läntinen Suomenlahti",
    type: ["Vierasvenesatama", "Kaivossaari"],
    notableFeature: "Entinen rautakaivossaari, jossa hylätty kaupunki ja majakka",
    description:
      "Jussarö on kiehtova saari, jossa on hylätty rautakaivos, aavekaupunki ja majakka. Nykyään kansallispuiston osana se tarjoaa vierasvenesataman vierailijoille, jotka tutkivat sen ainutlaatuista teollisuushistoriaa ja luontopolkuja.",
    hints: [
      "Tämä satama sijaitsee saarella, jossa on hylätty rautakaivos ja aavekaupunki",
      "Siellä on majakka ja se on nykyään osa kansallispuistoa",
      "Saarella on ainutlaatuinen teollisuushistoria ja luontopolkuja",
      "Nimi päättyy kirjaimeen 'ö'",
      "Se alkaa kirjaimella 'J'",
    ],
  },
  {
    id: 11,
    name: "Nötö",
    language: "fi",
    coordinates: { lat: 59.95, lng: 21.7667 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Perinteinen"],
    notableFeature: "Perinteinen saaristokylä, jossa puutaloja ja kivikirkko",
    description:
      "Nötö on yksi eteläisen Saaristomeren suuremmista saarista, jossa on perinteinen kylä, puutaloja ja 1750-luvulta peräisin oleva kivikirkko. Vierasvenesatama tarjoaa hyvät palvelut ja on suosittu pysähdyspaikka saaristossa risteileville.",
    hints: [
      "Tämä satama sijaitsee yhdellä eteläisen Saaristomeren suuremmista saarista",
      "Siellä on perinteinen kylä, jossa puutaloja",
      "Saarella on 1750-luvulta peräisin oleva kivikirkko",
      "Nimi tarkoittaa ruotsiksi 'Pähkinäsaari'",
      "Se alkaa kirjaimella 'N' ja päättyy kirjaimeen 'ö'",
    ],
  },
  {
    id: 12,
    name: "Pielavesi Harbor",
    language: "fi",
    coordinates: { lat: 63.2333, lng: 26.75 },
    region: "Pohjois-Savo",
    type: ["Sisävesisatama", "Järvisatama"],
    notableFeature: "Viehättävä pikkukaupungin satama Suomen järvialueella",
    description:
      "Pielaveden pikkukaupungissa Suomen järvialueella sijaitseva satama palvelee paikallisia veneilijöitä ja kesävieraita. Alue tunnetaan kauniista järvimaisemistaan ja se on osa laajaa Kymijoen vesistöä.",
    hints: [
      "Tämä satama sijaitsee pikkukaupungissa Suomen järvialueella",
      "Se on osa laajaa Kymijoen vesistöä",
      "Kaupunki ja satama jakavat saman nimen",
      "Se sijaitsee Pohjois-Savon maakunnassa",
      "Nimi alkaa kirjaimella 'P' ja päättyy kirjaimeen 'i'",
    ],
  },
  {
    id: 13,
    name: "Vänö",
    language: "fi",
    coordinates: { lat: 59.8667, lng: 21.9167 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Perinteinen"],
    notableFeature: "Syrjäinen perinteinen saariyhteisö, jossa pieni satama",
    description:
      "Vänö on syrjäinen saari, jossa on pieni ympärivuotinen väestö, joka ylläpitää perinteistä saaristoelämäntapaa. Vierasvenesatama on pieni mutta tarjoaa peruspalvelut, ja saarella on kaunista luontoa ja kävelypolkuja.",
    hints: [
      "Tämä satama sijaitsee syrjäisellä saarella, jossa on pieni ympärivuotinen väestö",
      "Saarella ylläpidetään perinteistä saaristoelämäntapaa",
      "Siellä on kaunista luontoa ja kävelypolkuja",
      "Nimi on hyvin lyhyt - vain 4 kirjainta",
      "Se alkaa kirjaimella 'V' ja päättyy kirjaimeen 'ö'",
    ],
  },
  {
    id: 14,
    name: "Aspö",
    language: "fi",
    coordinates: { lat: 60.2833, lng: 26.4 },
    region: "Itäinen Suomenlahti",
    type: ["Vierasvenesatama", "Linnoitussaari"],
    notableFeature: "Linnoitussaari lähellä Kotkaa, jolla on sotilashistoriaa",
    description:
      "Aspö on linnoitussaari lähellä Kotkaa, jolla on merkittävä sotilashistoria. Vierasvenesatama tarjoaa hyvät palvelut, ja vierailijat voivat tutkia vanhoja sotilasrakennelmia, bunkkereita ja kaunista rannikkoluontoa.",
    hints: [
      "Tämä satama sijaitsee linnoitussaarella lähellä Kotkaa",
      "Saarella on merkittävä sotilashistoria",
      "Vierailijat voivat tutkia vanhoja sotilasrakennelmia ja bunkkereita",
      "Nimi tarkoittaa ruotsiksi 'Haapasaari'",
      "Se alkaa kirjaimella 'A' ja päättyy kirjaimeen 'ö'",
    ],
  },
  {
    id: 15,
    name: "Tornio Marina",
    language: "fi",
    coordinates: { lat: 65.85, lng: 24.15 },
    region: "Lappi",
    type: ["Jokisatama", "Rajasatama"],
    notableFeature: "Pohjoisin satama Pohjanlahdella, Ruotsin rajalla",
    description:
      "Tornionjoen suulla Ruotsin rajalla sijaitseva satama on yksi Pohjanlahden pohjoisimmista. Se toimii porttina Suomen ja Ruotsin välillä ja tarjoaa palveluja veneilijöille, jotka tutkivat pohjoista Itämerta.",
    hints: [
      "Tämä satama sijaitsee joen suulla Ruotsin rajalla",
      "Se on yksi Pohjanlahden pohjoisimmista satamista",
      "Kaupunki tunnetaan rajanaapurikaupungistaan Ruotsin puolella",
      "Joki ja kaupunki jakavat saman nimen",
      "Nimi alkaa kirjaimella 'T'",
    ],
  },
  {
    id: 16,
    name: "Helsinki South Harbor",
    language: "fi",
    coordinates: { lat: 60.1674, lng: 24.9525 },
    region: "Helsingin seutu",
    type: ["Kauppasatama", "Matkustajaterminaali"],
    notableFeature: "Suomen vilkkain matkustajasatama Helsingin sydämessä",
    description:
      "Helsingin Eteläsatama on pääkaupungin tärkein matkustajasatama, josta liikennöidään Tukholmaan, Tallinnaan ja Pietariin. Se sijaitsee Kauppatorin vieressä ja sitä ympäröivät Helsingin maamerkit, kuten Presidentinlinna ja Helsingin tuomiokirkko.",
    hints: [
      "Tämä satama sijaitsee Suomen pääkaupungissa",
      "Se on merkittävä matkustajasatama, josta on lauttayhteyksiä naapurimaihin",
      "Se sijaitsee kuuluisan kauppatorin vieressä",
      "Satamaa ympäröivät maamerkit, kuten valkoinen tuomiokirkko",
      "Kaupungin nimi alkaa kirjaimella 'H'",
    ],
  },
  {
    id: 17,
    name: "Turku Harbor",
    language: "fi",
    coordinates: { lat: 60.4358, lng: 22.2242 },
    region: "Varsinais-Suomi",
    type: ["Kauppasatama", "Matkustajaterminaali", "Historiallinen"],
    notableFeature: "Suomen vanhin satama, josta on merkittävät lauttayhteydet Ruotsiin",
    description:
      "Turun satama on Suomen vanhin satama, jonka historia ulottuu 1200-luvulle. Nykyään se on merkittävä kauppasatama ja matkustajaterminaali, josta on säännölliset lauttayhteydet Tukholmaan. Satama sijaitsee lähellä Turun linnaa ja Aurajoen suuta.",
    hints: [
      "Tämä satama on Suomen vanhimmassa kaupungissa",
      "Sieltä on merkittävät lauttayhteydet Tukholmaan",
      "Se sijaitsee lähellä keskiaikaista linnaa",
      "Kaupunki oli aikoinaan Suomen pääkaupunki",
      "Kaupungin nimi alkaa kirjaimella 'T' ja siinä on 5 kirjainta",
    ],
  },
  {
    id: 18,
    name: "Kotka Harbor",
    language: "fi",
    coordinates: { lat: 60.4665, lng: 26.9456 },
    region: "Kymenlaakso",
    type: ["Kauppasatama", "Teollisuussatama"],
    notableFeature: "Merkittävä vientisatama, jolla on vahva merenkulkuperinne",
    description:
      "Kotkan satama on yksi Suomen merkittävimmistä vientisatamista, joka on erikoistunut metsäteollisuuden tuotteisiin. Kaupungilla on vahva merenkulkuperinne, joka näkyy sen Merimuseossa ja Merikeskus Vellamossa. Satama koostuu useista satama-alueista, kuten Mussalosta, Hietasesta ja Kantasatamasta.",
    hints: [
      "Tämä satama on yksi Suomen merkittävimmistä vientisatamista",
      "Kaupungissa on kuuluisa Merimuseo",
      "Se on erikoistunut metsäteollisuuden tuotteisiin",
      "Se sijaitsee Kaakkois-Suomessa",
      "Kaupungin nimi alkaa kirjaimella 'K' ja siinä on 5 kirjainta",
    ],
  },
  {
    id: 19,
    name: "Hanko West Harbor",
    language: "fi",
    coordinates: { lat: 59.8214, lng: 22.9086 },
    region: "Uusimaa",
    type: ["Vierasvenesatama", "Kauppasatama"],
    notableFeature: "Suomen mantereen eteläisin satama, jossa suosittu rantakohde",
    description:
      "Hangon Länsisatama sijaitsee Suomen mantereen eteläisimmässä kaupungissa, joka tunnetaan kauniista hiekkarannoistaan ja historiallisista puuhuviloistaan. Satama palvelee sekä kauppamerenkulkua että huviveneilijöitä, ja siellä on erinomaiset palvelut vieraileville purjeveneille.",
    hints: [
      "Tämä satama sijaitsee Suomen mantereen eteläisimmässä kaupungissa",
      "Kaupunki tunnetaan kauniista hiekkarannoistaan",
      "Siellä on historiallisia puuhuviloita 1800-luvun lopulta",
      "Se oli merkittävä matkustajasatama siirtolaisille Amerikkaan",
      "Kaupungin nimi alkaa kirjaimella 'H' ja siinä on 5 kirjainta",
    ],
  },
  {
    id: 20,
    name: "Oulu Harbor",
    language: "fi",
    coordinates: { lat: 65.0124, lng: 25.4138 },
    region: "Pohjois-Pohjanmaa",
    type: ["Kauppasatama", "Teollisuussatama"],
    notableFeature: "Pohjoisin ympärivuotinen kauppasatama Itämerellä",
    description:
      "Oulun satama on pohjoisin ympärivuotinen kauppasatama Itämerellä. Pohjoisesta sijainnistaan huolimatta satama pysyy toiminnassa läpi talven jäänmurtajien ansiosta. Se palvelee Pohjois-Suomen teollisuuden tarpeita ja on tärkeä vientikeskus.",
    hints: [
      "Tämä satama on pohjoisin ympärivuotinen kauppasatama Itämerellä",
      "Kaupunki on merkittävä teknologiakeskus Pohjois-Suomessa",
      "Satama pysyy toiminnassa läpi talven jäänmurtajien ansiosta",
      "Se sijaitsee samannimisen joen suulla",
      "Kaupungin nimi alkaa kirjaimella 'O' ja siinä on 4 kirjainta",
    ],
  },
  {
    id: 21,
    name: "Naantali Harbor",
    language: "fi",
    coordinates: { lat: 60.4667, lng: 22.0333 },
    region: "Varsinais-Suomi",
    type: ["Öljysatama", "Kauppasatama"],
    notableFeature: "Merkittävä öljysatama, jossa Suomen suurin öljynjalostamo",
    description:
      "Naantalin satama on Suomen suurimman öljynjalostamon kotipaikka ja toimii merkittävänä öljyn tuontiterminaalina. Syväväylän satama käsittelee myös kuivalastia ja matkustajaliikennettä. Naantalin pittoreski vanhakaupunki puutaloineen sijaitsee lähellä.",
    hints: [
      "Tämä satama on Suomen suurimman öljynjalostamon kotipaikka",
      "Se on merkittävä öljyn tuontiterminaali syväväylän satamalla",
      "Kaupunki tunnetaan pittoreskista vanhastakaupungistaan puutaloineen",
      "Se sijaitsee lähellä Turkua Varsinais-Suomessa",
      "Kaupunki tunnetaan myös Muumimaailma-teemapuistosta",
    ],
  },
  {
    id: 22,
    name: "Mariehamn West Harbor",
    language: "fi",
    coordinates: { lat: 60.0922, lng: 19.9281 },
    region: "Ahvenanmaa",
    type: ["Matkustajaterminaali", "Vierasvenesatama"],
    notableFeature: "Ahvenanmaan autonomisen alueen pääsatama",
    description:
      "Maarianhaminan Länsisatama on Ahvenanmaan autonomisen alueen pääsatama, joka palvelee matkustajalauttoja Suomen, Ruotsin ja Viron välillä. Satamassa on kuuluisa museolaiva Pommern ja se tarjoaa erinomaiset palvelut vieraileville purjeveneille.",
    hints: [
      "Tämä satama on Suomen autonomisen alueen pääsatama",
      "Siellä on kuuluisa museolaiva Pommern",
      "Kaupunki on saarimaakunnan pääkaupunki",
      "Alue on ruotsinkielinen",
      "Kaupungin nimi päättyy 'hamn'-sanaan (tarkoittaa satamaa ruotsiksi)",
    ],
  },
  {
    id: 23,
    name: "Rauma Harbor",
    language: "fi",
    coordinates: { lat: 61.1286, lng: 21.4931 },
    region: "Satakunta",
    type: ["Kauppasatama", "Teollisuussatama"],
    notableFeature: "Historiallinen satamakaupunki, jossa UNESCO:n maailmanperintökohteena oleva vanhakaupunki",
    description:
      "Rauman satama on merkittävä kauppasatama Suomen länsirannikolla. Kaupunki tunnetaan hyvin säilyneestä puutalovanhasta kaupungistaan, joka on UNESCO:n maailmanperintökohde. Satama on erikoistunut paperin, sellun ja konttiliikenteen käsittelyyn.",
    hints: [
      "Tämä satama sijaitsee kaupungissa, jonka vanhakaupunki on UNESCO:n maailmanperintökohde",
      "Kaupunki tunnetaan nyplätyn pitsin perinteestään",
      "Satama on erikoistunut paperin ja sellun vientiin",
      "Se sijaitsee Suomen länsirannikolla",
      "Kaupungin nimi alkaa kirjaimella 'R' ja siinä on 5 kirjainta",
    ],
  },
  {
    id: 24,
    name: "Vaasa Harbor",
    language: "fi",
    coordinates: { lat: 63.0833, lng: 21.6167 },
    region: "Pohjanmaa",
    type: ["Kauppasatama", "Matkustajaterminaali"],
    notableFeature: "Tärkeä satama, joka yhdistää Suomen Ruotsiin Pohjanlahden kapeimmassa kohdassa",
    description:
      "Vaasan satama toimii tärkeänä yhteytenä Suomen ja Ruotsin välillä, ja sieltä on säännölliset lauttayhteydet Uumajaan Pohjanlahden kapeimman kohdan yli. Satama käsittelee sekä matkustaja- että rahtiliikennettä ja on elintärkeä alueen teollisuudelle.",
    hints: [
      "Tästä satamasta on säännölliset lauttayhteydet Uumajaan Ruotsiin",
      "Se sijaitsee Pohjanlahden kapeimmassa kohdassa",
      "Kaupunki tunnetaan energiateknologiayritysten suuresta keskittymästä",
      "Se on Pohjanmaan maakunnan suurin kaupunki",
      "Kaupungin nimi alkaa kirjaimella 'V' ja siinä on 5 kirjainta",
    ],
  },
  {
    id: 25,
    name: "Kemi Harbor",
    language: "fi",
    coordinates: { lat: 65.7333, lng: 24.5667 },
    region: "Lappi",
    type: ["Teollisuussatama", "Kauppasatama"],
    notableFeature: "Pohjoisin kauppasatama Suomessa, jossa lumilinna-nähtävyys",
    description:
      "Kemin satama on yksi Suomen pohjoisimmista kauppasatamista, joka palvelee Lapin metsä- ja kaivosteollisuutta. Kaupunki tunnetaan vuosittaisesta lumilinnastaan ja jäänmurtajaristeilyistään jäätyneellä Pohjanlahdella.",
    hints: [
      "Tämä satama on yksi Suomen pohjoisimmista kauppasatamista",
      "Kaupunki tunnetaan vuosittaisesta lumilinnastaan",
      "Sieltä järjestetään jäänmurtajaristeilyjä jäätyneellä Pohjanlahdella",
      "Se palvelee Lapin metsä- ja kaivosteollisuutta",
      "Kaupungin nimi alkaa kirjaimella 'K' ja siinä on 4 kirjainta",
    ],
  },
  {
    id: 26,
    name: "Hamina Harbor",
    language: "fi",
    coordinates: { lat: 60.5667, lng: 27.2 },
    region: "Kymenlaakso",
    type: ["Kauppasatama", "Teollisuussatama"],
    notableFeature: "Syväsatama, jonka kaupungissa on pyöreä asemakaava",
    description:
      "Haminan satama on syväsatama Kaakkois-Suomessa, joka on erikoistunut nestebulkin, kaasun ja konttiliikenteen käsittelyyn. Kaupunki tunnetaan ainutlaatuisesta pyöreästä asemakaavastaan ja 1700-luvun tähdenmuotoisesta linnoituksestaan.",
    hints: [
      "Tämä satama on syväsatama Kaakkois-Suomessa",
      "Kaupungissa on ainutlaatuinen pyöreä asemakaava",
      "Siellä on 1700-luvun tähdenmuotoinen linnoitus",
      "Satama on erikoistunut nestebulkin ja kaasun käsittelyyn",
      "Kaupungin nimi alkaa kirjaimella 'H' ja siinä on 6 kirjainta",
    ],
  },
  {
    id: 27,
    name: "Porvoo Harbor",
    language: "fi",
    coordinates: { lat: 60.3917, lng: 25.6667 },
    region: "Uusimaa",
    type: ["Historiallinen satama", "Vierasvenesatama"],
    notableFeature: "Pittoreski satama, jossa historialliset punaiset ranta-aitat",
    description:
      "Porvoon satama tunnetaan pittoreskeista punaisista ranta-aitoistaan, jotka ovat peräisin 1700- ja 1800-luvuilta. Satama sijaitsee Porvoonjoen suulla, joka johtaa yhteen Suomen viehättävimmistä vanhoistakaupungeista värikkäine puutaloineen.",
    hints: [
      "Tämä satama tunnetaan pittoreskeista punaisista ranta-aitoistaan",
      "Se sijaitsee samannimisen joen suulla",
      "Kaupungissa on yksi Suomen viehättävimmistä vanhoistakaupungeista",
      "Se on Suomen toiseksi vanhin kaupunki",
      "Kaupungin nimi alkaa kirjaimella 'P' ja siinä on 6 kirjainta",
    ],
  },
  {
    id: 28,
    name: "Savonlinna Harbor",
    language: "fi",
    coordinates: { lat: 61.8667, lng: 28.8833 },
    region: "Etelä-Savo",
    type: ["Sisävesisatama", "Vierasvenesatama"],
    notableFeature: "Satama keskiaikaisen Olavinlinnan vieressä",
    description:
      "Savonlinnan satama sijaitsee Suomen järvialueen sydämessä, keskiaikaisen Olavinlinnan vieressä. Satama palvelee sekä Saimaan järvialueella liikennöiviä matkustaja-aluksia että huviveneilijöitä. Kaupunki tunnetaan vuosittaisista oopperajuhlistaan.",
    hints: [
      "Tämä satama sijaitsee keskiaikaisen linnan vieressä",
      "Se on Suomen järvialueen sydämessä",
      "Kaupungissa järjestetään kuuluisat vuosittaiset oopperajuhlat",
      "Se sijaitsee Saimaalla",
      "Kaupungin nimi tarkoittaa 'Savon linnaa'",
    ],
  },
  {
    id: 29,
    name: "Lahti Harbor",
    language: "fi",
    coordinates: { lat: 61.0333, lng: 25.65 },
    region: "Päijät-Häme",
    type: ["Sisävesisatama", "Vierasvenesatama"],
    notableFeature: "Merkittävä sisävesisatama Päijänteen eteläpäässä",
    description:
      "Lahden satama sijaitsee Päijänteen eteläpäässä, joka on Suomen toiseksi suurin järvi. Satama toimii porttina järvialueelle ja tarjoaa palveluja sekä matkustaja-aluksille että huviveneilijöille. Kaupunki tunnetaan talviurheiluperinteistään.",
    hints: [
      "Tämä satama sijaitsee Päijänteen eteläpäässä",
      "Kaupunki tunnetaan talviurheiluperinteistään",
      "Siellä järjestetään vuosittain kansainvälinen mäkihyppykilpailu",
      "Se on merkittävä sisävesisatama, joka toimii porttina järvialueelle",
      "Kaupungin nimi alkaa kirjaimella 'L' ja siinä on 5 kirjainta",
    ],
  },
  {
    id: 30,
    name: "Kuopio Harbor",
    language: "fi",
    coordinates: { lat: 62.8833, lng: 27.6833 },
    region: "Pohjois-Savo",
    type: ["Sisävesisatama", "Vierasvenesatama"],
    notableFeature: "Vilkas satama Suomen järvialueen sydämessä",
    description:
      "Kuopion satama on vilkas sisävesisatama Suomen järvialueen sydämessä. Se sijaitsee Kallavedellä, joka on osa Saimaan järvialuetta, ja palvelee matkustaja-aluksia ja huviveneilijöitä. Satama-alueella on ravintoloita, kahviloita ja kauppahalli.",
    hints: [
      "Tämä satama sijaitsee Kallavedellä",
      "Se on osa Saimaan järvialuetta",
      "Kaupunki tunnetaan kalatoristaan ja kauppahallista",
      "Se on kuuluisa paikallisesta kalaruoasta nimeltä 'kalakukko'",
      "Kaupungin nimi alkaa kirjaimella 'K' ja siinä on 6 kirjainta",
    ],
  },
  {
    id: 31,
    name: "Sysmä Harbor",
    language: "fi",
    coordinates: { lat: 61.5028, lng: 25.6856 },
    region: "Päijät-Häme",
    type: ["Sisävesisatama", "Vierasvenesatama"],
    notableFeature: "Viehättävä satama historiallisessa kunnassa Päijänteellä",
    description:
      "Sysmän satama on pittoreski sisävesisatama, joka sijaitsee historiallisessa Sysmän kunnassa Päijänteen itärannalla. Satama tarjoaa hyvät palvelut veneilijöille, mukaan lukien polttoaineen, sähkön ja jätehuollon. Läheisessä kylän keskustassa on ravintoloita, kauppoja ja historiallinen kirkko.",
    hints: [
      "Tämä satama sijaitsee historiallisessa kunnassa Päijänteellä",
      "Kunta tunnetaan kulttuuritapahtumistaan, kuten musiikkifestivaalista",
      "Se sijaitsee Suomen toiseksi suurimman järven itärannalla",
      "Satama on lähellä kylää, jossa on keskiaikainen kivikirkko",
      "Nimi alkaa kirjaimella 'S' ja päättyy kirjaimeen 'ä'",
    ],
  },
  {
    id: 32,
    name: "Loviisa Harbor",
    language: "fi",
    coordinates: { lat: 60.4569, lng: 26.2264 },
    region: "Uusimaa",
    type: ["Vierasvenesatama", "Historiallinen satama"],
    notableFeature: "Viehättävä pikkukaupungin satama, jossa puinen vanhakaupunki ja merenkulkuhistoriaa",
    description:
      "Loviisan satama palvelee viehättävää rannikkokaupunkia, joka tunnetaan hyvin säilyneestä puisesta vanhastakaupungistaan ja merenkulkuhistoriastaan. Vierasvenesatama tarjoaa hyvät palvelut vieraileville veneille ja on kävelymatkan päässä kaupungin keskustasta kahviloineen, ravintoloineen ja historiallisine kohteineen, kuten Svartholman merilinnoitus.",
    hints: [
      "Tämä satama sijaitsee rannikkokaupungissa, joka tunnetaan hyvin säilyneestä puisesta vanhastakaupungistaan",
      "Kaupunki on nimetty Ruotsin kuningattaren mukaan",
      "Se sijaitsee noin 90 km itään Helsingistä",
      "Kaupunki tunnetaan vuosittaisista historiallisista tapahtumistaan ja merenkulkufestivaaleistaan",
      "Nimi alkaa kirjaimella 'L' ja siinä on 7 kirjainta",
    ],
  },
  {
    id: 33,
    name: "Tammisaari Harbor",
    language: "fi",
    coordinates: { lat: 59.9758, lng: 23.4364 },
    region: "Uusimaa",
    type: ["Vierasvenesatama", "Saariston portti"],
    notableFeature: "Historiallinen satamakaupunki, joka toimii porttina läntisen Uudenmaan saaristoon",
    description:
      "Tammisaaren (ruotsiksi Ekenäs) satama sijaitsee pittoreskissa kaksikielisessä kaupungissa, joka toimii porttina läntisen Uudenmaan saaristoon. Vierasvenesatama sijaitsee aivan viehättävän vanhankaupungin vieressä, jossa on puutaloja, ravintoloita ja putiikkeja. Alue on osa Tammisaaren saariston kansallispuistoa.",
    hints: [
      "Tämä satama sijaitsee kaksikielisessä kaupungissa, joka toimii porttina saaristoon",
      "Kaupunki tunnetaan hyvin säilyneestä puisesta vanhastakaupungistaan",
      "Se on osa vuonna 2009 muodostettua Raaseporin kaupunkia",
      "Se sijaitsee lähellä kaupungin mukaan nimettyä kansallispuistoa",
      "Suomenkielinen nimi alkaa kirjaimella 'T', mutta se tunnetaan myös ruotsinkielisellä nimellään 'Ekenäs'",
    ],
  },
  {
    id: 34,
    name: "Uusikaupunki Harbor",
    language: "fi",
    coordinates: { lat: 60.8, lng: 21.4167 },
    region: "Varsinais-Suomi",
    type: ["Vierasvenesatama", "Kauppasatama"],
    notableFeature: "Historiallinen laivanrakennuskaupunki, jossa hyvin säilynyt puinen vanhakaupunki",
    description:
      "Uudenkaupungin (ruotsiksi Nystad) satama palvelee sekä huviveneilijöitä että kauppamerenkulkua. Kaupunki tunnetaan laivanrakennusperinteestään, autoteollisuudestaan ja hyvin säilyneestä puisesta vanhastakaupungistaan. Vierasvenesatama tarjoaa hyvät palvelut ja sijaitsee lähellä kaupungin keskustaa, jossa on merimuseo ja ravintoloita.",
    hints: [
      "Tämä satama sijaitsee historiallisessa laivanrakennuskaupungissa Varsinais-Suomessa",
      "Kaupunki tunnetaan nykyään autoteollisuudesta",
      "Siellä on hyvin säilynyt puinen vanhakaupunki",
      "Kaupungin nimi tarkoittaa kirjaimellisesti 'Uutta kaupunkia' suomeksi",
      "Pohjan sodan päättänyt rauhansopimus allekirjoitettiin täällä vuonna 1721",
    ],
  },
  {
    id: 35,
    name: "Kristiinankaupunki Harbor",
    language: "fi",
    coordinates: { lat: 62.2736, lng: 21.3758 },
    region: "Pohjanmaa",
    type: ["Vierasvenesatama", "Historiallinen satama"],
    notableFeature: "Hyvin säilynyt puukaupunki, jolla on rikas merenkulun kauppahistoria",
    description:
      "Kristiinankaupungin (ruotsiksi Kristinestad) satama palvelee viehättävää rannikkokaupunkia, jossa on yksi Suomen parhaiten säilyneistä puukaupunkikeskustoista. Vuonna 1649 perustetulla kaupungilla on rikas merenkulun kauppahistoria. Vierasvenesatama tarjoaa hyvät palvelut ja sijaitsee lähellä historiallista kaupungin keskustaa puutaloineen, kapeoine katuineen ja merellisine tunnelmineen.",
    hints: [
      "Tämä satama sijaitsee yhdessä Suomen parhaiten säilyneistä puukaupungeista",
      "Kaupunki perustettiin vuonna 1649 ja nimettiin kuningatar Kristiinan mukaan",
      "Se sijaitsee Pohjanmaalla länsirannikolla",
      "Kaupunki on virallisesti kaksikielinen, jossa on merkittävä ruotsinkielinen väestö",
      "Suomenkielinen nimi on melko pitkä (17 kirjainta) ja alkaa kirjaimella 'K'",
    ],
  },
  {
    id: 36,
    name: "Kaskinen Harbor",
    language: "fi",
    coordinates: { lat: 62.3833, lng: 21.2167 },
    region: "Pohjanmaa",
    type: ["Kauppasatama", "Vierasvenesatama"],
    notableFeature: "Suomen pinta-alaltaan pienin kaupunki, joka sijaitsee kokonaan saarella",
    description:
      "Kaskisten (ruotsiksi Kaskö) satama palvelee Suomen pinta-alaltaan pienintä kaupunkia, joka sijaitsee kokonaan saarella. Kaupungilla on vahva merenkulku- ja teollisuusperinne, syväväylän kauppasatama ja pieni vierasvenesatama. Kompakti kaupungin keskusta ruutukaavoineen ja puutaloineen on kävelymatkan päässä satamasta.",
    hints: [
      "Tämä satama sijaitsee Suomen pinta-alaltaan pienimmässä kaupungissa",
      "Kaupunki sijaitsee kokonaan saarella",
      "Siellä on syväväylän kauppasatama ja pieni vierasvenesatama",
      "Kaupungilla on vahva ruotsinkielinen perinne",
      "Nimi alkaa kirjaimella 'K' ja tarkoittaa 'pientä arkkua' suomeksi",
    ],
  },
  {
    id: 37,
    name: "Mikkeli Harbor",
    language: "fi",
    coordinates: { lat: 61.6875, lng: 27.2736 },
    region: "Etelä-Savo",
    type: ["Sisävesisatama", "Järvisatama"],
    notableFeature: "Maakuntapääkaupungin satama Saimaalla, jolla on historiallista merkitystä",
    description:
      "Mikkelin satama palvelee Etelä-Savon maakuntapääkaupunkia, joka sijaitsee Saimaan lahdella. Kaupungilla on historiallista merkitystä Suomen armeijan päämajana toisen maailmansodan aikana. Satama tarjoaa palveluja huviveneilijöille, jotka tutkivat Saimaan järvialuetta, ja on yhteydessä kaupungin keskustaan ravintoloineen, kauppoineen ja kulttuurinähtävyyksineen.",
    hints: [
      "Tämä satama palvelee maakuntapääkaupunkia, joka sijaitsee Saimaalla",
      "Kaupunki toimi Suomen armeijan päämajana toisen maailmansodan aikana",
      "Se sijaitsee Etelä-Savon maakunnassa",
      "Kaupungissa järjestetään merkittävä vuosittainen balettifestivaali",
      "Nimi alkaa kirjaimella 'M' ja siinä on 7 kirjainta",
    ],
  },
  {
    id: 38,
    name: "Joensuu Harbor",
    language: "fi",
    coordinates: { lat: 62.6, lng: 29.7667 },
    region: "Pohjois-Karjala",
    type: ["Sisävesisatama", "Jokisatama"],
    notableFeature: "Yliopistokaupungin satama Pielisjoen suulla Pyhäselällä",
    description:
      "Joensuun satama sijaitsee Pielisjoen suulla, jossa se laskee Pyhäselkään, joka on osa Saimaan järvialuetta. Kaupunki on Pohjois-Karjalan maakuntapääkaupunki ja yliopistokaupunki. Satama palvelee huviveneilijöitä ja sijaitsee lähellä kaupungin keskustaa toriaukioineen, kävelykatuineen ja kulttuurinähtävyyksineen.",
    hints: [
      "Tämä satama sijaitsee Pielisjoen suulla",
      "Kaupunki on Pohjois-Karjalan maakuntapääkaupunki",
      "Se on yliopistokaupunki, jossa on vilkas kulttuurielämä",
      "Satama on osa Saimaan järvialuetta",
      "Nimi tarkoittaa 'joen suuta' suomeksi",
    ],
  },
  {
    id: 39,
    name: "Jyväskylä Harbor",
    language: "fi",
    coordinates: { lat: 62.2333, lng: 25.7333 },
    region: "Keski-Suomi",
    type: ["Sisävesisatama", "Järvisatama"],
    notableFeature: "Yliopistokaupungin satama Päijänteen pohjoispäässä",
    description:
      "Jyväskylän satama sijaitsee Päijänteen pohjoispäässä Keski-Suomessa. Kaupunki tunnetaan yliopistostaan, Alvar Aallon arkkitehtuurista ja 'Suomen Ateenana' koulutuksellisen merkityksensä vuoksi. Satama palvelee Päijännettä tutkivia huviveneilijöitä ja on lähellä kaupungin keskustaa ravintoloineen, kauppoineen ja kulttuurinähtävyyksineen.",
    hints: [
      "Tämä satama sijaitsee Päijänteen pohjoispäässä",
      "Kaupunki tunnetaan 'Suomen Ateenana' koulutuksellisen merkityksensä vuoksi",
      "Se on kuuluisa Alvar Aallon suunnittelemasta arkkitehtuurista",
      "Kaupungissa järjestetään vuosittainen rallikilpailu",
      "Nimi alkaa kirjaimella 'J' ja päättyy kirjaimeen 'ä'",
    ],
  },
  {
    id: 40,
    name: "Hämeenlinna Harbor",
    language: "fi",
    coordinates: { lat: 61.0, lng: 24.4667 },
    region: "Kanta-Häme",
    type: ["Sisävesisatama", "Järvisatama"],
    notableFeature: "Historiallisen kaupungin satama Vanajavedellä lähellä keskiaikaista linnaa",
    description:
      "Hämeenlinnan satama sijaitsee Vanajavedellä yhdessä Suomen vanhimmista sisämaakaupungeista. Kaupunki tunnetaan keskiaikaisesta linnastaan, Hämeen linnasta, ja säveltäjä Jean Sibeliuksen syntymäpaikkana. Satama palvelee huviveneilijöitä ja on yhteydessä kaupungin keskustaan ravintoloineen, kauppoineen ja kulttuurinähtävyyksineen.",
    hints: [
      "Tämä satama sijaitsee Vanajavedellä yhdessä Suomen vanhimmista sisämaakaupungeista",
      "Kaupunki tunnetaan keskiaikaisesta linnastaan",
      "Se on säveltäjä Jean Sibeliuksen syntymäpaikka",
      "Kaupungin nimi tarkoittaa kirjaimellisesti 'Hämeen linnaa' suomeksi",
      "Nimi alkaa kirjaimella 'H' ja päättyy kirjaimeen 'a'",
    ],
  },
  {
    id: 41,
    name: "Tampere Harbor",
    language: "fi",
    coordinates: { lat: 61.5, lng: 23.7667 },
    region: "Pirkanmaa",
    type: ["Sisävesisatama", "Järvisatama"],
    notableFeature: "Teollisuuskaupungin satama Pyhäjärvellä, jossa kunnostettuja tehdasrakennuksia",
    description:
      "Tampereen satama (Laukontori) sijaitsee Pyhäjärvellä Suomen suurimmassa sisämaakaupungissa. Kaupunki tunnetaan 'Suomen Manchesterina' teollisen perintönsä vuoksi, ja se on rakennettu kahden järven väliin, joita yhdistää Tammerkosken koski. Satama-alueella on kunnostettuja tehdasrakennuksia, ravintoloita ja se on lähellä kaupungin keskustaa kauppoineen ja kulttuurinähtävyyksineen.",
    hints: [
      "Tämä satama sijaitsee Pyhäjärvellä Suomen suurimmassa sisämaakaupungissa",
      "Kaupunki tunnetaan 'Suomen Manchesterina' teollisen perintönsä vuoksi",
      "Se on rakennettu kahden järven väliin, joita yhdistää koski",
      "Satama-alueella on kunnostettuja tehdasrakennuksia",
      "Kaupungin nimi alkaa kirjaimella 'T' ja siinä on 7 kirjainta",
    ],
  },
  {
    id: 42,
    name: "Raahe Harbor",
    language: "fi",
    coordinates: { lat: 64.6833, lng: 24.4833 },
    region: "Pohjois-Pohjanmaa",
    type: ["Kauppasatama", "Vierasvenesatama"],
    notableFeature: "Historiallinen rannikkokaupunki, jossa hyvin säilynyt puinen vanhakaupunki ja teollisuussatama",
    description:
      "Raahen satama palvelee sekä teollisuuden kuljetuksia että huviveneilyä. Kaupungissa on hyvin säilynyt puinen vanhakaupunki, Pekkatori, ja vahva merenkulkuperinne, joka näkyy sen merimuseossa. Vierasvenesatama tarjoaa palveluja vieraileville veneilijöille ja on kävelymatkan päässä kaupungin keskustasta.",
    hints: [
      "Tämä satama palvelee historiallista rannikkokaupunkia, jossa on hyvin säilynyt puinen vanhakaupunki",
      "Kaupungilla on vahva merenkulkuperinne ja merimuseo",
      "Siellä on sekä teollisuussatama että vierasvenesatama",
      "Se sijaitsee Pohjois-Pohjanmaalla Pohjanlahdella",
      "Nimi alkaa kirjaimella 'R' ja siinä on 5 kirjainta",
    ],
  },
  {
    id: 43,
    name: "Kokkola Harbor",
    language: "fi",
    coordinates: { lat: 63.8383, lng: 23.1317 },
    region: "Keski-Pohjanmaa",
    type: ["Kauppasatama", "Vierasvenesatama"],
    notableFeature: "Tärkeä vientisatama, jossa hyvin säilynyt puinen vanhakaupunki",
    description:
      "Kokkolan satama (ruotsiksi Karleby) on tärkeä vientisatama Pohjanlahdella. Kaupungissa on hyvin säilynyt puinen vanhakaupunki, Neristan, ja vahva merenkulku- ja kauppaperinne. Vierasvenesatama tarjoaa palveluja vieraileville veneilijöille ja on lähellä kaupungin keskustaa kauppoineen, ravintoloineen ja kulttuurinähtävyyksineen.",
    hints: [
      "Tämä satama on tärkeä vientisatama Pohjanlahdella",
      "Kaupungissa on hyvin säilynyt puinen vanhakaupunki nimeltä Neristan",
      "Se on Keski-Pohjanmaan maakunnan pääkaupunki",
      "Kaupunki on virallisesti kaksikielinen, jolla on sekä suomen- että ruotsinkielinen nimi",
      "Suomenkielinen nimi alkaa kirjaimella 'K' ja siinä on 7 kirjainta",
    ],
  },
  {
    id: 44,
    name: "Pietarsaari Harbor",
    language: "fi",
    coordinates: { lat: 63.6667, lng: 22.7 },
    region: "Pohjanmaa",
    type: ["Kauppasatama", "Vierasvenesatama"],
    notableFeature: "Kaksikielinen rannikkokaupunki, jolla on vahva merenkulku- ja laivanrakennusperinne",
    description:
      "Pietarsaaren satama (ruotsiksi Jakobstad) palvelee kaksikielistä rannikkokaupunkia, jolla on vahva merenkulku- ja laivanrakennusperinne. Vierasvenesatama tarjoaa hyvät palvelut vieraileville veneilijöille ja on lähellä kaupungin keskustaa kauppoineen, ravintoloineen ja nähtävyyksineen, kuten kasvitieteellinen puutarha Skata ja Nanoq-arktinen museo.",
    hints: [
      "Tämä satama palvelee kaksikielistä rannikkokaupunkia, jolla on vahva merenkulkuperinne",
      "Kaupungissa on ruotsinkielinen enemmistö ja suomenkielinen vähemmistö",
      "Siellä on kasvitieteellinen puutarha nimeltä Skata ja Nanoq-arktinen museo",
      "Kaupunki nimettiin Jacob De la Gardien mukaan 1600-luvulla",
      "Suomenkielinen nimi alkaa kirjaimella 'P', mutta se tunnetaan kansainvälisesti paremmin ruotsinkielisellä nimellään 'Jakobstad'",
    ],
  },
  {
    id: 45,
    name: "Uusikaarlepyy Harbor",
    language: "fi",
    coordinates: { lat: 63.5222, lng: 22.5303 },
    region: "Pohjanmaa",
    type: ["Jokisatama", "Vierasvenesatama"],
    notableFeature: "Pieni kaksikielinen kaupunki Lapuanjoen suulla",
    description:
      "Uudenkaarlepyyn satama (ruotsiksi Nykarleby) sijaitsee Lapuanjoen suulla. Tämä pieni, pääosin ruotsinkielinen kaupunki on viehättävä keskusta puutaloineen ja rikkaalla kulttuuriperinnöllä. Pieni vierasvenesatama tarjoaa peruspalvelut vieraileville veneilijöille.",
    hints: [
      "Tämä satama sijaitsee Lapuanjoen suulla",
      "Kaupunki on pääosin ruotsinkielinen",
      "Se on yksi Suomen pienimmistä kaupungeista",
      "Runoilija Zacharias Topelius syntyi täällä",
      "Suomenkielinen nimi on melko pitkä ja alkaa kirjaimella 'U', mutta se tunnetaan myös ruotsinkielisellä nimellään 'Nykarleby'",
    ],
  },
  {
    id: 46,
    name: "Kalajoki Harbor",
    language: "fi",
    coordinates: { lat: 64.2567, lng: 23.9486 },
    region: "Pohjois-Pohjanmaa",
    type: ["Vierasvenesatama", "Rantakohde"],
    notableFeature: "Suosittu matkailukohde, jossa laajat hiekkarannat",
    description:
      "Kalajoen satama palvelee suosittua rannikon matkailukohdetta, joka tunnetaan laajoista hiekkarannoistaan, hiekkadyyneistään ja lomakeskuksistaan. Vierasvenesatama tarjoaa hyvät palvelut vieraileville veneilijöille ja sijaitsee lähellä ranta-aluetta ravintoloineen, aktiviteetteineen ja majoitusvaihtoehtoineen.",
    hints: [
      "Tämä satama palvelee suosittua rannikon matkailukohdetta, joka tunnetaan hiekkarannoistaan",
      "Alueella on Suomelle epätavallisia hiekkadyynejä",
      "Se on suosittu kesälomakohde",
      "Se sijaitsee Pohjois-Pohjanmaalla Pohjanlahdella",
      "Nimi alkaa kirjaimella 'K' ja tarkoittaa 'kalajokea' suomeksi",
    ],
  },
  {
    id: 47,
    name: "Lappeenranta Harbor",
    language: "fi",
    coordinates: { lat: 61.0681, lng: 28.1889 },
    region: "Etelä-Karjala",
    type: ["Sisävesisatama", "Kanavan portti"],
    notableFeature: "Vilkas satama-alue linnoituksen lähellä, portti Saimaan kanavalle",
    description:
      "Lappeenrannan satama on vilkas sisävesisatama Saimaalla, joka toimii porttina Saimaan kanavalle, joka yhdistää Venäjälle. Kaupungissa on historiallinen linnoitus ja vilkas satama-alue ravintoloineen, risteilyaluksineen ja toreineen. Satama tarjoaa hyvät palvelut huviveneilijöille, jotka tutkivat Saimaan järvialuetta.",
    hints: [
      "Tämä satama on Saimaalla ja toimii porttina kanavalle, joka yhdistää Venäjälle",
      "Kaupungissa on historiallinen linnoitus, joka kohoaa sataman yläpuolella",
      "Siellä on vilkas satama-alue ravintoloineen ja toreineen",
      "Kaupunki tunnetaan teknillisestä yliopistostaan",
      "Nimi päättyy sanaan 'ranta', joka tarkoittaa 'rantaa' suomeksi",
    ],
  },
  {
    id: 48,
    name: "Imatra Harbor",
    language: "fi",
    coordinates: { lat: 61.1722, lng: 28.7756 },
    region: "Etelä-Karjala",
    type: ["Sisävesisatama", "Jokisatama"],
    notableFeature: "Satama lähellä voimakkaita Imatrankosken koskia Venäjän rajalla",
    description:
      "Imatran satama sijaitsee Saimaalla lähellä voimakkaita Imatrankosken koskia ja lähellä Venäjän rajaa. Kaupunki kehittyi vesivoimalaitoksen ympärille ja sillä on ainutlaatuinen teollinen perintö. Satama palvelee huviveneilijöitä, jotka tutkivat Saimaan järvialueen itäosia.",
    hints: [
      "Tämä satama on Saimaalla lähellä voimakkaita koskia",
      "Kaupunki on hyvin lähellä Venäjän rajaa",
      "Se kehittyi vesivoimalaitoksen ympärille",
      "Kosket ovat kuuluisa luonnonnähtävyys, joka on inspiroinut taiteilijoita",
      "Nimi alkaa kirjaimella 'I' ja siinä on 6 kirjainta",
    ],
  },
  {
    id: 49,
    name: "Kemi-Tornio Harbor",
    language: "fi",
    coordinates: { lat: 65.7361, lng: 24.5653 },
    region: "Lappi",
    type: ["Kauppasatama", "Teollisuussatama"],
    notableFeature: "Merkittävä teollisuussatama, joka palvelee Lapin metsä- ja kaivosteollisuutta",
    description:
      "Kemi-Tornion satama on merkittävä teollisuussatamakompleksi, joka palvelee Lapin metsä- ja kaivosteollisuutta. Alue tunnetaan sellu- ja paperitehtaistaan, teräksen tuotannosta ja Pohjois-Suomen logistiikkakeskuksena. Satama käsittelee irtolastia, kontteja ja teollisuustuotteita.",
    hints: [
      "Tämä satama on merkittävä teollisuussatamakompleksi Lapissa",
      "Se palvelee Pohjois-Suomen metsä- ja kaivosteollisuutta",
      "Alue tunnetaan sellu- ja paperitehtaistaan ja teräksen tuotannosta",
      "Se on nimetty kahden naapurikaupungin mukaan",
      "Toinen kaupungeista tunnetaan vuosittaisesta lumilinnastaan",
    ],
  },
  {
    id: 50,
    name: "Rovaniemi Harbor",
    language: "fi",
    coordinates: { lat: 66.5, lng: 25.7167 },
    region: "Lappi",
    type: ["Jokisatama", "Arktinen satama"],
    notableFeature: "Satama 'joulupukin virallisessa kotikaupungissa' napapiirillä",
    description:
      "Rovaniemen satama sijaitsee Kemijoen varrella Suomen Lapin pääkaupungissa, joka tunnetaan 'joulupukin virallisena kotikaupunkina'. Kaupunki sijaitsee napapiirillä ja toimii porttina pohjoiseen erämaahan. Pieni satama palvelee jokiveneitä ja on lähellä kaupungin keskustaa kauppoineen, ravintoloineen ja nähtävyyksineen, kuten Arktikum-museo.",
    hints: [
      "Tämä satama sijaitsee Kemijoen varrella Suomen Lapin pääkaupungissa",
      "Kaupunki tunnetaan 'joulupukin virallisena kotikaupunkina'",
      "Se sijaitsee napapiirillä",
      "Kaupunki rakennettiin lähes kokonaan uudelleen toisen maailmansodan jälkeen",
      "Nimi alkaa kirjaimella 'R' ja siinä on 9 kirjainta",
    ],
  },
  {
    id: 51,
    name: "Parainen Harbor",
    language: "fi",
    coordinates: { lat: 60.3, lng: 22.3 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Teollisuussatama"],
    notableFeature: "Portti Saariston Rengastielle, jolla on kalkkiteollisuuden perintö",
    description:
      "Paraisten satama (ruotsiksi Pargas) toimii porttina Saariston Rengastielle, suositulle reitille, joka yhdistää Saaristomeren saaret. Kaupungilla on vahva kalkkiteollisuuden perintö, jossa on suuri louhos ja sementtitehdas. Vierasvenesatama tarjoaa hyvät palvelut veneilijöille ja on lähellä kaupungin keskustaa kauppoineen ja ravintoloineen.",
    hints: [
      "Tämä satama toimii porttina Saariston Rengastielle",
      "Kaupungilla on vahva kalkkiteollisuuden perintö, jossa on suuri louhos",
      "Se on kaksikielinen kunta, jolla on sekä suomen- että ruotsinkielinen nimi",
      "Se on lähtöpiste Saaristomeren tutkimiseen autolla ja lautalla",
      "Suomenkielinen nimi alkaa kirjaimella 'P', ruotsinkielinen nimi on 'Pargas'",
    ],
  },
  {
    id: 52,
    name: "Korppoo Harbor",
    language: "fi",
    coordinates: { lat: 60.1667, lng: 21.5833 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Lauttasatama"],
    notableFeature: "Tärkeä pysähdyspaikka Saariston Rengastiellä, jossa historiallinen puukirkko",
    description:
      "Korppoon satama (ruotsiksi Korpo) on tärkeä pysähdyspaikka Saariston Rengastiellä, joka palvelee sekä huviveneilijöitä että autolauttoja. Saarella on 1400-luvulta peräisin oleva historiallinen puukirkko ja perinteinen saaristokylä. Vierasvenesatama tarjoaa hyvät palvelut ja on lähellä kylän keskustaa pienine kauppoineen ja ravintoloineen.",
    hints: [
      "Tämä satama on tärkeä pysähdyspaikka Saariston Rengastiellä",
      "Saarella on 1400-luvulta peräisin oleva historiallinen puukirkko",
      "Se on kaksikielinen kunta, jolla on sekä suomen- että ruotsinkielinen nimi",
      "Se on osa Paraisten/Pargas-kaupunkia vuodesta 2009",
      "Suomenkielinen nimi alkaa kirjaimella 'K', ruotsinkielinen nimi on 'Korpo'",
    ],
  },
  {
    id: 53,
    name: "Nauvo Harbor",
    language: "fi",
    coordinates: { lat: 60.1917, lng: 21.9083 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Saariston keskus"],
    notableFeature: "Suosittu saariston keskus, jossa vilkas vierasvenesatama ja historiallinen kirkko",
    description:
      "Nauvon satama (ruotsiksi Nagu) on yksi Saaristomeren suosituimmista vierasvenesatamista, joka toimii keskuksena aluetta tutkiville veneilijöille. Saarella on keskiaikainen kivikirkko ja vilkas kylän keskusta. Vierasvenesatama tarjoaa erinomaiset palvelut ja sitä ympäröivät ravintolat, kahvilat ja kaupat, luoden vilkkaan merellisen tunnelman kesäisin.",
    hints: [
      "Tämä satama on yksi Saaristomeren suosituimmista vierasvenesatamista",
      "Saarella on keskiaikainen kivikirkko",
      "Siellä on vilkas kylän keskusta ravintoloineen ja kauppoineen",
      "Se on kaksikielinen kunta, jolla on sekä suomen- että ruotsinkielinen nimi",
      "Suomenkielinen nimi alkaa kirjaimella 'N', ruotsinkielinen nimi on 'Nagu'",
    ],
  },
  {
    id: 54,
    name: "Houtskär Harbor",
    language: "fi",
    coordinates: { lat: 60.2167, lng: 21.3667 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Perinteinen"],
    notableFeature: "Syrjäinen saaristosaari, jossa perinteisiä puutaloja ja kirkko",
    description:
      "Houtskärin satama (suomeksi Houtskari) palvelee syrjäistä saarta ulkosaaristossa. Saarella on perinteisiä puutaloja, 1700-luvulta peräisin oleva puukirkko ja kauniita saaristomaisemia. Vierasvenesatama tarjoaa peruspalvelut vieraileville veneilijöille ja on lähellä pientä kylän keskustaa.",
    hints: [
      "Tämä satama palvelee syrjäistä saarta ulkosaaristossa",
      "Saarella on perinteisiä puutaloja ja puukirkko",
      "Se on pääosin ruotsinkielinen alue",
      "Se on osa Paraisten/Pargas-kaupunkia vuodesta 2009",
      "Ruotsinkielinen nimi alkaa kirjaimella 'H', suomenkielinen nimi on 'Houtskari'",
    ],
  },
  {
    id: 55,
    name: "Iniö Harbor",
    language: "fi",
    coordinates: { lat: 60.4, lng: 21.4167 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Syrjäinen saari"],
    notableFeature: "Suomen pienin entinen kunta, jossa perinteinen saaristokulttuuri",
    description:
      "Iniön satama palvelee yhtä Saaristomeren syrjäisimmistä asutuista saariryhmistä. Aiemmin Suomen pienin kunta, alue ylläpitää vahvaa perinteistä saaristokulttuuria. Vierasvenesatama tarjoaa peruspalvelut vieraileville veneilijöille ja on lähellä pientä kylän keskustaa kirkkoineen ja paikallisine palveluineen.",
    hints: [
      "Tämä satama palvelee yhtä Saaristomeren syrjäisimmistä asutuista saariryhmistä",
      "Se oli aiemmin Suomen pienin kunta",
      "Alue ylläpitää vahvaa perinteistä saaristokulttuuria",
      "Se on osa Paraisten/Pargas-kaupunkia vuodesta 2009",
      "Nimi on sama sekä suomeksi että ruotsiksi",
    ],
  },
  {
    id: 56,
    name: "Kasnäs Harbor",
    language: "fi",
    coordinates: { lat: 59.9167, lng: 22.4167 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Luontomatkailu"],
    notableFeature: "Moderni satama lähellä Saaristomeren kansallispuiston opastuskeskusta",
    description:
      "Kasnäsin satama on moderni satama, joka sijaitsee Kemiönsaaren niemenkärjessä ja toimii porttina Saaristomeren kansallispuistoon. Alueella on Sinisimpukan opastuskeskus, kylpylähotelli ja erinomaiset palvelut veneilijöille. Satama on suosittu lähtöpiste Saaristomeren eteläosien tutkimiseen.",
    hints: [
      "Tämä satama sijaitsee Kemiönsaaren niemenkärjessä",
      "Se toimii porttina Saaristomeren kansallispuistoon",
      "Alueella on Sinisimpukan opastuskeskus",
      "Siellä on kylpylähotelli ja erinomaiset palvelut veneilijöille",
      "Nimi alkaa kirjaimella 'K' ja päättyy kirjaimeen 's'",
    ],
  },
  {
    id: 57,
    name: "Kustavi Harbor",
    language: "fi",
    coordinates: { lat: 60.55, lng: 21.3667 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Kalastuskylä"],
    notableFeature: "Historiallinen kalastuskylä Saaristomeren pohjoisreunalla",
    description:
      "Kustavin satama palvelee historiallista kalastuskylää Saaristomeren pohjoisreunalla. Alueella on vahva merenkulkuperinne ja se tunnetaan perinteisestä kalansavustuksestaan. Vierasvenesatama tarjoaa hyvät palvelut vieraileville veneilijöille ja on lähellä kylän keskustaa ravintoloineen, jotka ovat erikoistuneet paikallisiin kalaruokiin.",
    hints: [
      "Tämä satama palvelee historiallista kalastuskylää Saaristomeren pohjoisreunalla",
      "Alueella on vahva merenkulkuperinne ja se tunnetaan perinteisestä kalansavustuksesta",
      "Se on suosittu kesäkohde, jossa on paljon kesämökkejä",
      "Kunnassa on enemmän saaria kuin mannerta",
      "Nimi alkaa kirjaimella 'K' ja siinä on 7 kirjainta",
    ],
  },
  {
    id: 58,
    name: "Rymättylä Harbor",
    language: "fi",
    coordinates: { lat: 60.3833, lng: 21.9333 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Kalastuskylä"],
    notableFeature: "Perinteinen kalastuskylä, jossa keskiaikainen kivikirkko",
    description:
      "Rymättylän satama palvelee perinteistä kalastuskylää samannimisellä saarella. Alueella on vahva kalastusperinne ja siellä on 1400-luvulta peräisin oleva keskiaikainen kivikirkko. Vierasvenesatama tarjoaa palveluja vieraileville veneilijöille ja on lähellä kylän keskustaa pienine kauppoineen ja ravintoloineen.",
    hints: [
      "Tämä satama palvelee perinteistä kalastuskylää saarella",
      "Alueella on vahva kalastusperinne",
      "Siellä on 1400-luvulta peräisin oleva keskiaikainen kivikirkko",
      "Se on nykyään osa Naantalin kaupunkia",
      "Nimi alkaa kirjaimella 'R' ja päättyy kirjaimeen 'ä'",
    ],
  },
  {
    id: 59,
    name: "Velkua Harbor",
    language: "fi",
    coordinates: { lat: 60.45, lng: 21.6833 },
    region: "Saaristomeri",
    type: ["Vierasvenesatama", "Saariyhteisö"],
    notableFeature: "Idyllinen saariyhteisö, jossa puukirkko ja perinteiset maisemat",
    description:
      "Velkuan satama palvelee idyllistä saariyhteisöä, joka koostuu useista asutuista saarista. Alueella on 1700-luvulta peräisin oleva puukirkko ja perinteisiä saaristomaisemia. Pieni vierasvenesatama tarjoaa peruspalvelut vieraileville veneilijöille ja on lähellä pääkylää paikallisine palveluineen.",
    hints: [
      "Tämä satama palvelee idyllistä saariyhteisöä, joka koostuu useista asutuista saarista",
      "Alueella on 1700-luvulta peräisin oleva puukirkko",
      "Se oli aiemmin yksi Suomen pienimmistä kunnista",
      "Se on nykyään osa Naantalin kaupunkia",
      "Nimi alkaa kirjaimella 'V' ja siinä on 6 kirjainta",
    ],
  },
  {
    id: 60,
    name: "Merikarvia Harbor",
    language: "fi",
    coordinates: { lat: 61.8583, lng: 21.4917 },
    region: "Satakunta",
    type: ["Kalastussatama", "Vierasvenesatama"],
    notableFeature: "Perinteinen kalastuskaupunki, jossa puisia venevajoja ja vahva merenkulkuperinne",
    description:
      "Merikarvian satama palvelee perinteistä kalastuskaupunkia Selkämeren rannikolla. Alue tunnetaan puisista venevajoistaan, vahvasta kalastusperinteestään ja joesta, joka on kuuluisa lohikalastuksesta. Vierasvenesatama tarjoaa palveluja vieraileville veneilijöille ja on lähellä kaupungin keskustaa puukirkkoineen ja paikallisine palveluineen.",
    hints: [
      "Tämä satama palvelee perinteistä kalastuskaupunkia Selkämeren rannikolla",
      "Alue tunnetaan puisista venevajoistaan ja vahvasta kalastusperinteestään",
      "Siellä on joki, joka on kuuluisa lohikalastuksesta",
      "Kaupungin nimi tarkoittaa kirjaimellisesti 'merikarikkoa' suomeksi",
      "Nimi alkaa kirjaimella 'M' ja siinä on 10 kirjainta",
    ],
  },
]

// Function to fetch harbor data
export async function fetchHarborData(language = "fi") {
  // In a real app, this would be an API call
  return new Promise((resolve) => {
    // Simulate network delay
    setTimeout(() => {
      resolve(harbors)
    }, 800)
  })
}

