// Finnish harbors and marinas database - Swedish version
// Comprehensive collection of coastal and inland harbors across Finland

export const harbors = [
  {
    id: 1,
    name: "Elisaari",
    language: "sv",
    coordinates: { lat: 60.0167, lng: 23.9333 },
    region: "Västra Nyland",
    type: ["Gästhamn", "Naturhamn"],
    notableFeature: "Vacker ö med restaurang och naturstigar",
    description:
      "Elisaari är en populär gästhamn i den västra skärgården i Nyland. Ön erbjuder vackra naturstigar, en restaurang och bastuanläggningar för besökare. Det är en fridfull destination med bra skydd från vindar.",
    hints: [
      "Denna hamn ligger på en ö i Västra Nyland",
      "Ön har en restaurang och naturstigar",
      "Det är ett populärt resmål för familjebåtturer",
      "Namnet börjar med 'E'",
      "Den ligger nära Ingå",
    ],
  },
  {
    id: 2,
    name: "Örö",
    language: "sv",
    coordinates: { lat: 59.8089, lng: 22.3347 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Historisk"],
    notableFeature: "Tidigare militärö med unik natur och historiska befästningar",
    description:
      "Örö är en fascinerande tidigare militärö i yttre skärgården som öppnades för allmänheten 2015. Den har sällsynt flora, historiska kustartilleribefästningar och en gästhamn med moderna faciliteter.",
    hints: [
      "Denna hamn ligger på en tidigare militärö",
      "Den ligger i Skärgårdshavets nationalpark",
      "Ön har sällsynt flora och kustartilleribefästningar",
      "Namnet är mycket kort",
      "Det börjar med bokstaven 'Ö'",
    ],
  },
  {
    id: 3,
    name: "Jurmo",
    language: "sv",
    coordinates: { lat: 59.8272, lng: 21.5772 },
    region: "Yttre Skärgårdshavet",
    type: ["Gästhamn", "Traditionell"],
    notableFeature: "Avlägsen ö med unik geologi och traditionell skärgårdsby",
    description:
      "Jurmo är en avlägsen, karg ö i yttre skärgården med ett distinkt landskap format av istida glaciärer. Den har en liten traditionell by, en gästhamn och är känd för sin unika natur och fågelskådningsmöjligheter.",
    hints: [
      "Denna hamn ligger på en avlägsen, karg ö i yttre skärgården",
      "Ön har ett distinkt landskap format av istida glaciärer",
      "Den är känd för fågelskådning och unik natur",
      "Ön har en liten traditionell by",
      "Namnet rimmar med 'Turmo'",
    ],
  },
  {
    id: 4,
    name: "Päijänne Marina",
    language: "sv",
    coordinates: { lat: 61.6167, lng: 25.5667 },
    region: "Päijänne",
    type: ["Insjöhamn", "Sjöhamn"],
    notableFeature: "Stor marina på Finlands näst största sjö",
    description:
      "Belägen vid stranden av sjön Päijänne, denna marina fungerar som ett nav för insjöbåtfarare som utforskar Finlands näst största sjö. Den erbjuder omfattande tjänster inklusive bränsle, underhåll och en restaurang.",
    hints: [
      "Denna marina ligger vid Finlands näst största sjö",
      "Det är en populär utgångspunkt för att utforska den närliggande nationalparken",
      "Sjön delar namn med marinan",
      "Den ligger i centrala Finland",
      "Namnet börjar med 'P'",
    ],
  },
  {
    id: 5,
    name: "Själö",
    language: "sv",
    coordinates: { lat: 60.2361, lng: 21.9444 },
    region: "Inre Skärgårdshavet",
    type: ["Gästhamn", "Historisk"],
    notableFeature: "Tidigare leprasjukhusö med träkyrka och forskningsstation",
    description:
      "Själö (Seili på finska) har en mörk historia som tidigare leprakoloni och mentalsjukhusö. Idag inhyser den en biologisk forskningsstation och erbjuder en gästhamn för besökare. Träkyrkan och de gamla sjukhusbyggnaderna berättar öns fascinerande historia.",
    hints: [
      "Denna hamn ligger på en ö med en mörk historia som tidigare leprakoloni",
      "Idag inhyser den en biologisk forskningsstation",
      "Den har en träkyrka och gamla sjukhusbyggnader",
      "Öns namn är olika på finska och svenska",
      "På svenska börjar det med 'S' och har 5 bokstäver",
    ],
  },
  {
    id: 6,
    name: "Utö",
    language: "sv",
    coordinates: { lat: 59.7833, lng: 21.3667 },
    region: "Yttre Skärgårdshavet",
    type: ["Gästhamn", "Fyrö"],
    notableFeature: "Finlands sydligaste året-runt bebodda ö med en historisk fyr",
    description:
      "Utö är Finlands sydligaste året-runt bebodda ö, med en historisk fyr, en liten by och en gästhamn. Ön har en rik maritim historia och erbjuder en glimt av det autentiska livet i yttre skärgården.",
    hints: [
      "Denna hamn ligger på Finlands sydligaste året-runt bebodda ö",
      "Ön har en historisk fyr",
      "Den har en rik maritim historia och en liten by",
      "Namnet är mycket kort - bara tre bokstäver",
      "Det börjar med 'U'",
    ],
  },
  {
    id: 7,
    name: "Saimen Harbor",
    language: "sv",
    coordinates: { lat: 61.8667, lng: 28.8833 },
    region: "Saimen",
    type: ["Insjöhamn", "Sjöhamn"],
    notableFeature: "Marina på Finlands största sjö, hem till utrotningshotade saimenvikare",
    description:
      "Denna hamn ligger vid sjön Saimen, Finlands största sjö och hem till den utrotningshotade saimenvikaren. Marinan erbjuder tjänster för båtfarare som utforskar det vidsträckta Saimenvattensystemet med sina tusentals öar.",
    hints: [
      "Denna marina ligger vid Finlands största sjö",
      "Sjön är hem till en utrotningshotad art av sötvattenssäl",
      "Sjösystemet har tusentals öar och holmar",
      "Den ligger i östra Finland",
      "Namnet börjar med 'S'",
    ],
  },
  {
    id: 8,
    name: "Kökar",
    language: "sv",
    coordinates: { lat: 59.9167, lng: 20.9 },
    region: "Ålands skärgård",
    type: ["Gästhamn", "Kulturell"],
    notableFeature: "Avlägsen Åländsk ö med medeltida klosterruiner",
    description:
      "Kökar är en av de mest avlägsna bebodda öarna i Ålands skärgård. Den har medeltida franciskanerklosterruiner, en vacker kyrka och flera gästhamnar. Ön har ett rikt fiskarv och unika kulturella traditioner.",
    hints: [
      "Denna hamn ligger på en av de mest avlägsna bebodda öarna i Ålands skärgård",
      "Ön har medeltida franciskanerklosterruiner",
      "Den har ett rikt fiskarv och unika kulturella traditioner",
      "Namnet är fem bokstäver långt",
      "Det börjar med 'K' och har ett 'ö' i sig",
    ],
  },
  {
    id: 9,
    name: "Enare Marina",
    language: "sv",
    coordinates: { lat: 68.9, lng: 27.0333 },
    region: "Lappland",
    type: ["Insjöhamn", "Arktisk hamn"],
    notableFeature: "Nordligaste större marinan i Finland, vid sjön Enare",
    description:
      "Belägen vid stranden av sjön Enare i finska Lappland, detta är en av de nordligaste marinorna i Finland. Den fungerar som en bas för att utforska vildmarken i norra Lappland och de heliga platserna för den inhemska samiska befolkningen.",
    hints: [
      "Denna marina är en av de nordligaste i Finland",
      "Den ligger vid en stor sjö i Lappland",
      "Sjön och marinan delar samma namn",
      "Den är nära heliga platser för den inhemska samiska befolkningen",
      "Namnet börjar med 'E'",
    ],
  },
  {
    id: 10,
    name: "Jussarö",
    language: "sv",
    coordinates: { lat: 59.8333, lng: 23.5667 },
    region: "Västra Finska viken",
    type: ["Gästhamn", "Gruvö"],
    notableFeature: "Tidigare järngruvsö med spökstad och fyr",
    description:
      "Jussarö är en fascinerande ö med en övergiven järngruva, en spökstad och en fyr. Nu en del av en nationalpark, den erbjuder en gästhamn för besökare som utforskar dess unika industrihistoria och naturstigar.",
    hints: [
      "Denna hamn ligger på en ö med en övergiven järngruva och spökstad",
      "Den har en fyr och är nu en del av en nationalpark",
      "Ön har en unik industrihistoria och naturstigar",
      "Namnet slutar med 'ö'",
      "Det börjar med 'J'",
    ],
  },
  {
    id: 11,
    name: "Nötö",
    language: "sv",
    coordinates: { lat: 59.95, lng: 21.7667 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Traditionell"],
    notableFeature: "Traditionell skärgårdsby med trähus och stenkyrka",
    description:
      "Nötö är en av de större öarna i södra Skärgårdshavet med en traditionell by, trähus och en stenkyrka från 1750-talet. Gästhamnen erbjuder bra service och är ett populärt stopp för skärgårdskryssare.",
    hints: [
      "Denna hamn ligger på en av de större öarna i södra Skärgårdshavet",
      "Den har en traditionell by med trähus",
      "Ön har en stenkyrka från 1750-talet",
      "Namnet betyder 'Nötö' på svenska",
      "Det börjar med 'N' och slutar med 'ö'",
    ],
  },
  {
    id: 12,
    name: "Pielavesi Harbor",
    language: "sv",
    coordinates: { lat: 63.2333, lng: 26.75 },
    region: "Norra Savolax",
    type: ["Insjöhamn", "Sjöhamn"],
    notableFeature: "Charmig småstadshamn i det finska sjödistriktet",
    description:
      "Belägen i den lilla staden Pielavesi i det finska sjödistriktet, denna hamn betjänar lokala båtfarare och sommarbesökare. Området är känt för sina vackra sjölandskap och är en del av det omfattande Kymmene älvs vattensystem.",
    hints: [
      "Denna hamn ligger i en liten stad i det finska sjödistriktet",
      "Den är en del av det omfattande Kymmene älvs vattensystem",
      "Staden och hamnen delar samma namn",
      "Den ligger i Norra Savolax-regionen",
      "Namnet börjar med 'P' och slutar med 'i'",
    ],
  },
  {
    id: 13,
    name: "Vänö",
    language: "sv",
    coordinates: { lat: 59.8667, lng: 21.9167 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Traditionell"],
    notableFeature: "Avlägsen traditionell ösamhälle med en liten hamn",
    description:
      "Vänö är en avlägsen ö med en liten året-runt befolkning som upprätthåller traditionella skärgårdslivsstilar. Gästhamnen är liten men erbjuder grundläggande tjänster, och ön har vacker natur och vandringsleder.",
    hints: [
      "Denna hamn ligger på en avlägsen ö med en liten året-runt befolkning",
      "Ön upprätthåller traditionella skärgårdslivsstilar",
      "Den har vacker natur och vandringsleder",
      "Namnet är mycket kort - bara 4 bokstäver",
      "Det börjar med 'V' och slutar med 'ö'",
    ],
  },
  {
    id: 14,
    name: "Aspö",
    language: "sv",
    coordinates: { lat: 60.2833, lng: 26.4 },
    region: "Östra Finska viken",
    type: ["Gästhamn", "Fästningsö"],
    notableFeature: "Fästningsö nära Kotka med militärhistoria",
    description:
      "Aspö är en fästningsö nära Kotka med en betydande militärhistoria. Gästhamnen erbjuder bra service, och besökare kan utforska gamla militäranläggningar, bunkrar och vacker kustnatur.",
    hints: [
      "Denna hamn ligger på en fästningsö nära Kotka",
      "Ön har en betydande militärhistoria",
      "Besökare kan utforska gamla militäranläggningar och bunkrar",
      "Namnet betyder 'Aspö' på svenska",
      "Det börjar med 'A' och slutar med 'ö'",
    ],
  },
  {
    id: 15,
    name: "Torneå Marina",
    language: "sv",
    coordinates: { lat: 65.85, lng: 24.15 },
    region: "Lappland",
    type: ["Flodhamn", "Gränshamn"],
    notableFeature: "Nordligaste marinan i Bottniska viken, vid svenska gränsen",
    description:
      "Belägen vid mynningen av Torne älv på gränsen till Sverige, denna marina är en av de nordligaste i Bottniska viken. Den fungerar som en port mellan Finland och Sverige och erbjuder tjänster för båtfarare som utforskar norra Östersjön.",
    hints: [
      "Denna marina ligger vid mynningen av en älv på gränsen till Sverige",
      "Den är en av de nordligaste marinorna i Bottniska viken",
      "Staden är känd för sin gränstvillingstad med Sverige",
      "Älven och staden delar samma namn",
      "Namnet börjar med 'T'",
    ],
  },
  {
    id: 16,
    name: "Helsingfors Södra Hamnen",
    language: "sv",
    coordinates: { lat: 60.1674, lng: 24.9525 },
    region: "Helsingforsregionen",
    type: ["Handelshamn", "Passagerarterminal"],
    notableFeature: "Finlands livligaste passagerarhamn i hjärtat av Helsingfors",
    description:
      "Helsingfors Södra Hamn (Eteläsatama) är huvudstadens viktigaste passagerarhamn, som betjänar färjor till Stockholm, Tallinn och St. Petersburg. Belägen intill Salutorget, den är omgiven av Helsingfors landmärken inklusive Presidentpalatset och Helsingfors domkyrka.",
    hints: [
      "Denna hamn ligger i Finlands huvudstad",
      "Det är en stor passagerarhamn med färjor till grannländer",
      "Den ligger intill ett berömt torg",
      "Hamnen är omgiven av ikoniska landmärken inklusive en vit katedral",
      "Stadens namn börjar med 'H'",
    ],
  },
  {
    id: 17,
    name: "Åbo Hamn",
    language: "sv",
    coordinates: { lat: 60.4358, lng: 22.2242 },
    region: "Egentliga Finland",
    type: ["Handelshamn", "Passagerarterminal", "Historisk"],
    notableFeature: "Finlands äldsta hamn med stora färjeförbindelser till Sverige",
    description:
      "Åbo hamn är Finlands äldsta hamn med en historia som sträcker sig tillbaka till 1200-talet. Idag är det en stor handelshamn och passagerarterminal med regelbundna färjeförbindelser till Stockholm. Hamnen ligger nära Åbo slott och mynningen av Aura å.",
    hints: [
      "Denna hamn är i Finlands äldsta stad",
      "Den har stora färjeförbindelser till Stockholm",
      "Den ligger nära en medeltida borg",
      "Staden var en gång Finlands huvudstad",
      "Stadens namn börjar med 'Å' och har 3 bokstäver",
    ],
  },
  {
    id: 18,
    name: "Kotka Hamn",
    language: "sv",
    coordinates: { lat: 60.4665, lng: 26.9456 },
    region: "Kymmenedalen",
    type: ["Handelshamn", "Industrihamn"],
    notableFeature: "Stor exporthamn med ett starkt maritimt arv",
    description:
      "Kotka hamn är en av Finlands största exporthamnar, specialiserad på skogsindustriprodukter. Staden har ett starkt maritimt arv, vilket återspeglas i dess Sjöfartsmuseum och Maritimcentret Vellamo. Hamnen består av flera hamnområden inklusive Mussalo, Hietanen och Kantasatama.",
    hints: [
      "Denna hamn är en av Finlands största exporthamnar",
      "Staden har ett berömt Sjöfartsmuseum",
      "Den är specialiserad på skogsindustriprodukter",
      "Den ligger i sydöstra Finland",
      "Stadens namn börjar med 'K' och har 5 bokstäver",
    ],
  },
  {
    id: 19,
    name: "Hangö Västra Hamnen",
    language: "sv",
    coordinates: { lat: 59.8214, lng: 22.9086 },
    region: "Nyland",
    type: ["Gästhamn", "Handelshamn"],
    notableFeature: "Finlands sydligaste fastlandshamn med en populär badort",
    description:
      "Hangö Västra Hamnen ligger i Finlands sydligaste fastlandsstad, känd för sina vackra sandstränder och historiska trävillor. Hamnen betjänar både kommersiell sjöfart och fritidsbåtar, med utmärkta faciliteter för besökande båtar.",
    hints: [
      "Denna hamn ligger i Finlands sydligaste fastlandsstad",
      "Staden är känd för sina vackra sandstränder",
      "Den har historiska trävillor från sent 1800-tal",
      "Det var platsen för en stor passagerarhamn för emigranter till Amerika",
      "Stadens namn börjar med 'H' och har 5 bokstäver",
    ],
  },
  {
    id: 20,
    name: "Uleåborg Hamn",
    language: "sv",
    coordinates: { lat: 65.0124, lng: 25.4138 },
    region: "Norra Österbotten",
    type: ["Handelshamn", "Industrihamn"],
    notableFeature: "Nordligaste året-runt handelshamnen i Östersjön",
    description:
      "Uleåborg hamn är den nordligaste året-runt handelshamnen i Östersjön. Trots sitt nordliga läge förblir hamnen operativ året runt tack vare isbrytare. Den betjänar norra Finlands industriella behov och är ett viktigt exportnav.",
    hints: [
      "Denna hamn är den nordligaste året-runt handelshamnen i Östersjön",
      "Staden är ett stort teknologinav i norra Finland",
      "Hamnen förblir operativ året runt tack vare isbrytare",
      "Den ligger vid mynningen av en älv med samma namn som staden",
      "Stadens finska namn börjar med 'O' och har 4 bokstäver",
    ],
  },
  {
    id: 21,
    name: "Nådendal Hamn",
    language: "sv",
    coordinates: { lat: 60.4667, lng: 22.0333 },
    region: "Egentliga Finland",
    type: ["Oljehamn", "Handelshamn"],
    notableFeature: "Stor oljehamn med Finlands största oljeraffinaderi",
    description:
      "Nådendal hamn är hem till Finlands största oljeraffinaderi och fungerar som en stor oljeimportterminal. Djupvattenhamnen hanterar också torrlast och passagerartrafik. Den pittoreska gamla staden i Nådendal med sina trähus ligger i närheten.",
    hints: [
      "Denna hamn är hem till Finlands största oljeraffinaderi",
      "Det är en stor oljeimportterminal med en djupvattenhamn",
      "Staden är känd för sin pittoreska gamla stad med trähus",
      "Den ligger nära Åbo i Egentliga Finland",
      "Staden är också känd för Muminvärlden temapark",
    ],
  },
  {
    id: 22,
    name: "Mariehamn Västra Hamnen",
    language: "sv",
    coordinates: { lat: 60.0922, lng: 19.9281 },
    region: "Åland",
    type: ["Passagerarterminal", "Gästhamn"],
    notableFeature: "Huvudhamn för det autonoma Åland",
    description:
      "Mariehamn Västra Hamnen är huvudhamnen för det autonoma Åland, som betjänar passagerarfärjor mellan Finland, Sverige och Estland. Hamnen är hem till det berömda museifartyget Pommern och erbjuder utmärkta faciliteter för besökande båtar.",
    hints: [
      "Denna hamn är huvudhamnen för en autonom region i Finland",
      "Den är hem till det berömda museifartyget Pommern",
      "Staden är huvudstad i en öprovins",
      "Regionen är svensktalande",
      "Stadens namn slutar med 'hamn' (som betyder hamn på svenska)",
    ],
  },
  {
    id: 23,
    name: "Raumo Hamn",
    language: "sv",
    coordinates: { lat: 61.1286, lng: 21.4931 },
    region: "Satakunta",
    type: ["Handelshamn", "Industrihamn"],
    notableFeature: "Historisk hamnstad med UNESCO världsarvslistad gammal stad",
    description:
      "Raumo hamn är en betydande handelshamn på Finlands västkust. Staden är känd för sin välbevarade trähusgamla stad, som är ett UNESCO världsarv. Hamnen är specialiserad på papper, pappersmassa och containertrafik.",
    hints: [
      "Denna hamn är i en stad med en UNESCO världsarvslistad gammal stad",
      "Staden är känd för sin tradition av knyppling",
      "Hamnen är specialiserad på papper och pappersmasseexport",
      "Den ligger på Finlands västkust",
      "Stadens namn börjar med 'R' och har 5 bokstäver",
    ],
  },
  {
    id: 24,
    name: "Vasa Hamn",
    language: "sv",
    coordinates: { lat: 63.0833, lng: 21.6167 },
    region: "Österbotten",
    type: ["Handelshamn", "Passagerarterminal"],
    notableFeature: "Viktig hamn som förbinder Finland med Sverige över den smalaste punkten av Bottniska viken",
    description:
      "Vasa hamn fungerar som en viktig länk mellan Finland och Sverige, med regelbundna färjeförbindelser till Umeå över den smalaste punkten av Bottniska viken. Hamnen hanterar både passagerar- och godstrafik och är vital för regionens industri.",
    hints: [
      "Denna hamn har regelbundna färjeförbindelser till Umeå, Sverige",
      "Den ligger vid den smalaste punkten av Bottniska viken",
      "Staden är känd för sin höga koncentration av energiteknikföretag",
      "Det är den största staden i Österbottenregionen",
      "Stadens namn börjar med 'V' och har 4 bokstäver",
    ],
  },
  {
    id: 25,
    name: "Kemi Hamn",
    language: "sv",
    coordinates: { lat: 65.7333, lng: 24.5667 },
    region: "Lappland",
    type: ["Industrihamn", "Handelshamn"],
    notableFeature: "Nordligaste handelshamnen i Finland med en snöslottsattraktion",
    description:
      "Kemi hamn är en av de nordligaste handelshamnarna i Finland, som betjänar skogs- och gruvindustrierna i Lappland. Staden är känd för sitt årliga snöslott och isbrytarkryssningar i den frusna Bottniska viken.",
    hints: [
      "Denna hamn är en av de nordligaste handelshamnarna i Finland",
      "Staden är känd för sitt årliga snöslott",
      "Den erbjuder isbrytarkryssningar i den frusna Bottniska viken",
      "Den betjänar skogs- och gruvindustrierna i Lappland",
      "Stadens namn börjar med 'K' och har 4 bokstäver",
    ],
  },
  {
    id: 26,
    name: "Fredrikshamn",
    language: "sv",
    coordinates: { lat: 60.5667, lng: 27.2 },
    region: "Kymmenedalen",
    type: ["Handelshamn", "Industrihamn"],
    notableFeature: "Djupvattenhamn med en cirkulär stadsplan",
    description:
      "Fredrikshamn är en djupvattenhamn i sydöstra Finland, specialiserad på flytande bulk, gas och containertrafik. Staden är känd för sin unika cirkulära stadsplan och stjärnformade fästning från 1700-talet.",
    hints: [
      "Denna hamn är en djupvattenhamn i sydöstra Finland",
      "Staden har en unik cirkulär stadsplan",
      "Den har en stjärnformad fästning från 1700-talet",
      "Hamnen är specialiserad på flytande bulk och gas",
      "Stadens finska namn börjar med 'H' och har 6 bokstäver",
    ],
  },
  {
    id: 27,
    name: "Borgå Hamn",
    language: "sv",
    coordinates: { lat: 60.3917, lng: 25.6667 },
    region: "Nyland",
    type: ["Historisk hamn", "Gästhamn"],
    notableFeature: "Pittoresk hamn med historiska röda strandmagasin",
    description:
      "Borgå hamn är känd för sina pittoreska röda strandmagasin från 1700- och 1800-talen. Hamnen ligger vid mynningen av Borgå å, som leder till en av Finlands mest charmiga gamla städer med färgglada trähus.",
    hints: [
      "Denna hamn är känd för sina pittoreska röda strandmagasin",
      "Den ligger vid mynningen av en å med samma namn som staden",
      "Staden har en av Finlands mest charmiga gamla städer",
      "Det är Finlands näst äldsta stad",
      "Stadens namn börjar med 'B' och har 5 bokstäver",
    ],
  },
  {
    id: 28,
    name: "Nyslott Hamn",
    language: "sv",
    coordinates: { lat: 61.8667, lng: 28.8833 },
    region: "Södra Savolax",
    type: ["Insjöhamn", "Gästhamn"],
    notableFeature: "Hamn intill den medeltida Olofsborg",
    description:
      "Nyslott hamn ligger i hjärtat av Finlands sjödistrikt, intill den medeltida Olofsborg. Hamnen betjänar både passagerarfartyg som navigerar i Saimenvattensystemet och fritidsbåtar. Staden är berömd för sin årliga operafestival.",
    hints: [
      "Denna hamn ligger intill en medeltida borg",
      "Den är i hjärtat av Finlands sjödistrikt",
      "Staden är värd för en berömd årlig operafestival",
      "Den ligger vid sjön Saimen",
      "Stadens namn betyder 'Nyslott' på svenska",
    ],
  },
  {
    id: 29,
    name: "Lahtis Hamn",
    language: "sv",
    coordinates: { lat: 61.0333, lng: 25.65 },
    region: "Päijänne-Tavastland",
    type: ["Insjöhamn", "Gästhamn"],
    notableFeature: "Stor insjöhamn vid södra änden av sjön Päijänne",
    description:
      "Lahtis hamn ligger vid södra änden av sjön Päijänne, Finlands näst största sjö. Hamnen fungerar som en port till sjösystemet och erbjuder tjänster för både passagerarfartyg och fritidsbåtar. Staden är känd för sina vintersporttraditioner.",
    hints: [
      "Denna hamn ligger vid södra änden av sjön Päijänne",
      "Staden är känd för sina vintersporttraditioner",
      "Den är värd för en årlig internationell skidtävling",
      "Det är en stor insjöhamn som fungerar som en port till ett sjösystem",
      "Stadens namn börjar med 'L' och har 6 bokstäver",
    ],
  },
  {
    id: 30,
    name: "Kuopio Hamn",
    language: "sv",
    coordinates: { lat: 62.8833, lng: 27.6833 },
    region: "Norra Savolax",
    type: ["Insjöhamn", "Gästhamn"],
    notableFeature: "Livlig hamn i hjärtat av det finska sjödistriktet",
    description:
      "Kuopio hamn är en livlig insjöhamn i hjärtat av det finska sjödistriktet. Belägen vid sjön Kallavesi, en del av Saimenvattensystemet, betjänar den passagerarfartyg och fritidsbåtar. Hamnområdet har restauranger, caféer och en saluhall.",
    hints: [
      "Denna hamn ligger vid sjön Kallavesi",
      "Den är en del av Saimenvattensystemet",
      "Staden är känd för sin fiskmarknad och saluhall",
      "Den är berömd för en speciell lokal fiskpaj kallad 'kalakukko'",
      "Stadens namn börjar med 'K' och har 6 bokstäver",
    ],
  },
  {
    id: 31,
    name: "Sysmä Hamn",
    language: "sv",
    coordinates: { lat: 61.5028, lng: 25.6856 },
    region: "Päijänne-Tavastland",
    type: ["Insjöhamn", "Gästhamn"],
    notableFeature: "Charmig hamn i den historiska kommunen vid sjön Päijänne",
    description:
      "Sysmä hamn är en pittoresk insjöhamn belägen i den historiska kommunen Sysmä på östra stranden av sjön Päijänne. Hamnen erbjuder bra service för båtfarare inklusive bränsle, el och avfallshantering. Det närliggande bycentrumet har restauranger, butiker och en historisk kyrka.",
    hints: [
      "Denna hamn ligger i en historisk kommun vid sjön Päijänne",
      "Kommunen är känd för sina kulturevenemang inklusive en musikfestival",
      "Den ligger på östra stranden av Finlands näst största sjö",
      "Hamnen är nära en by med en medeltida stenkyrka",
      "Namnet börjar med 'S' och slutar med 'ä'",
    ],
  },
  {
    id: 32,
    name: "Lovisa Hamn",
    language: "sv",
    coordinates: { lat: 60.4569, lng: 26.2264 },
    region: "Nyland",
    type: ["Gästhamn", "Historisk hamn"],
    notableFeature: "Charmig småstadshamn med trähusgamla stad och maritim historia",
    description:
      "Lovisa hamn betjänar den charmiga kuststaden känd för sin välbevarade trähusgamla stad och maritima historia. Gästhamnen erbjuder bra service för besökande båtar och ligger inom gångavstånd från stadens centrum med dess caféer, restauranger och historiska platser inklusive Svartholms sjöfästning.",
    hints: [
      "Denna hamn är i en kuststad känd för sin välbevarade trähusgamla stad",
      "Staden namngavs efter en svensk drottning",
      "Den ligger cirka 90 km öster om Helsingfors",
      "Staden är känd för sina årliga historiska evenemang och maritima festivaler",
      "Namnet börjar med 'L' och har 6 bokstäver",
    ],
  },
  {
    id: 33,
    name: "Ekenäs Hamn",
    language: "sv",
    coordinates: { lat: 59.9758, lng: 23.4364 },
    region: "Nyland",
    type: ["Gästhamn", "Skärgårdsport"],
    notableFeature: "Historisk hamnstad som fungerar som en port till västra Nylands skärgård",
    description:
      "Ekenäs hamn (Tammisaari på finska) ligger i en pittoresk tvåspråkig stad som fungerar som en port till västra Nylands skärgård. Gästhamnen ligger precis intill den charmiga gamla staden med trähus, restauranger och butiker. Området är en del av Ekenäs skärgårds nationalpark.",
    hints: [
      "Denna hamn är i en tvåspråkig stad som fungerar som en port till en skärgård",
      "Staden är känd för sin välbevarade trähusgamla stad",
      "Den är en del av staden Raseborg som bildades 2009",
      "Den ligger nära en nationalpark uppkallad efter staden",
      "Det svenska namnet börjar med 'E', men den är också känd under sitt finska namn 'Tammisaari'",
    ],
  },
  {
    id: 34,
    name: "Nystad Hamn",
    language: "sv",
    coordinates: { lat: 60.8, lng: 21.4167 },
    region: "Egentliga Finland",
    type: ["Gästhamn", "Handelshamn"],
    notableFeature: "Historisk skeppsbyggnadsstad med en välbevarad trähusgamla stad",
    description:
      "Nystad hamn (Uusikaupunki på finska) betjänar både fritidsbåtar och kommersiell sjöfart. Staden är känd för sin skeppsbyggnadstradition, biltillverkning och välbevarade trähusgamla stad. Gästhamnen erbjuder bra service och ligger nära stadens centrum med dess sjöfartsmuseum och restauranger.",
    hints: [
      "Denna hamn är i en historisk skeppsbyggnadsstad i Egentliga Finland",
      "Staden är nu känd för biltillverkning",
      "Den har en välbevarad trähusgamla stad",
      "Stadens namn betyder bokstavligen 'Ny stad' på svenska",
      "Fredsfördraget som avslutade Stora nordiska kriget undertecknades här 1721",
    ],
  },
  {
    id: 35,
    name: "Kristinestad Hamn",
    language: "sv",
    coordinates: { lat: 62.2736, lng: 21.3758 },
    region: "Österbotten",
    type: ["Gästhamn", "Historisk hamn"],
    notableFeature: "Välbevarad trästad med en rik maritim handelshistoria",
    description:
      "Kristinestad hamn (Kristiinankaupunki på finska) betjänar en charmig kuststad med ett av de bäst bevarade trästadscentrumen i Finland. Grundad 1649, staden har en rik maritim handelshistoria. Gästhamnen erbjuder bra service och ligger nära det historiska stadscentrumet med dess trähus, smala gator och maritima atmosfär.",
    hints: [
      "Denna hamn är i en av de bäst bevarade trästäderna i Finland",
      "Staden grundades 1649 och namngavs efter drottning Kristina av Sverige",
      "Den ligger i Österbotten på västkusten",
      "Staden är officiellt tvåspråkig med en betydande svensktalande befolkning",
      "Det svenska namnet börjar med 'K' och har 12 bokstäver",
    ],
  },
  {
    id: 36,
    name: "Kaskö Hamn",
    language: "sv",
    coordinates: { lat: 62.3833, lng: 21.2167 },
    region: "Österbotten",
    type: ["Handelshamn", "Gästhamn"],
    notableFeature: "Finlands minsta stad till ytan, belägen helt på en ö",
    description:
      "Kaskö hamn (Kaskinen på finska) betjänar Finlands minsta stad till ytan, belägen helt på en ö. Staden har ett starkt maritimt och industriellt arv, med en djupvattenhandelshamn och en liten gästhamn. Det kompakta stadscentrumet med dess rutnätsplan och trähus ligger inom gångavstånd från hamnen.",
    hints: [
      "Denna hamn är i Finlands minsta stad till ytan",
      "Staden är belägen helt på en ö",
      "Den har en djupvattenhandelshamn och en liten gästhamn",
      "Staden har ett starkt svensktalande arv",
      "Namnet börjar med 'K' och betyder 'liten kista' på svenska",
    ],
  },
  {
    id: 37,
    name: "St. Michel Hamn",
    language: "sv",
    coordinates: { lat: 61.6875, lng: 27.2736 },
    region: "Södra Savolax",
    type: ["Insjöhamn", "Sjöhamn"],
    notableFeature: "Regionhuvudstadens hamn vid Saimen med historisk betydelse",
    description:
      "St. Michel hamn betjänar regionhuvudstaden för Södra Savolax, belägen vid en vik av sjön Saimen. Staden har historisk betydelse som högkvarter för den finska armén under andra världskriget. Hamnen erbjuder tjänster för fritidsbåtar som utforskar Saimenvattensystemet och är ansluten till stadens centrum med dess restauranger, butiker och kulturella attraktioner.",
    hints: [
      "Denna hamn betjänar en regionhuvudstad belägen vid Saimen",
      "Staden var högkvarter för den finska armén under andra världskriget",
      "Den ligger i Södra Savolax-regionen",
      "Staden är värd för en stor årlig balettfestival",
      "Det svenska namnet börjar med 'S' och har 10 bokstäver",
    ],
  },
  {
    id: 38,
    name: "Joensuu Hamn",
    language: "sv",
    coordinates: { lat: 62.6, lng: 29.7667 },
    region: "Norra Karelen",
    type: ["Insjöhamn", "Flodhamn"],
    notableFeature: "Universitetsstads hamn vid mynningen av Pielisjoki-floden vid sjön Pyhäselkä",
    description:
      "Joensuu hamn ligger vid mynningen av Pielisjoki-floden där den flyter in i sjön Pyhäselkä, en del av Saimenvattensystemet. Staden är regionhuvudstaden för Norra Karelen och en universitetsstad. Hamnen betjänar fritidsbåtar och ligger nära stadens centrum med dess torg, gågator och kulturella attraktioner.",
    hints: [
      "Denna hamn ligger vid mynningen av Pielisjoki-floden",
      "Staden är regionhuvudstaden för Norra Karelen",
      "Det är en universitetsstad med en livlig kulturscen",
      "Hamnen är en del av Saimenvattensystemet",
      "Namnet betyder 'flodens mynning' på finska",
    ],
  },
  {
    id: 39,
    name: "Jyväskylä Hamn",
    language: "sv",
    coordinates: { lat: 62.2333, lng: 25.7333 },
    region: "Mellersta Finland",
    type: ["Insjöhamn", "Sjöhamn"],
    notableFeature: "Universitetsstads hamn vid norra änden av sjön Päijänne",
    description:
      "Jyväskylä hamn ligger vid norra änden av sjön Päijänne i Mellersta Finland. Staden är känd för sitt universitet, Alvar Aalto-arkitektur och som 'Finlands Aten' på grund av dess utbildningsmässiga betydelse. Hamnen betjänar fritidsbåtar som utforskar sjön Päijänne och ligger nära stadens centrum med dess restauranger, butiker och kulturella attraktioner.",
    hints: [
      "Denna hamn ligger vid norra änden av sjön Päijänne",
      "Staden är känd som 'Finlands Aten' på grund av dess utbildningsmässiga betydelse",
      "Den är berömd för arkitektur designad av Alvar Aalto",
      "Staden är värd för en årlig rallytävling",
      "Namnet börjar med 'J' och slutar med 'ä'",
    ],
  },
  {
    id: 40,
    name: "Tavastehus Hamn",
    language: "sv",
    coordinates: { lat: 61.0, lng: 24.4667 },
    region: "Egentliga Tavastland",
    type: ["Insjöhamn", "Sjöhamn"],
    notableFeature: "Historisk stads hamn vid sjön Vanajavesi nära en medeltida borg",
    description:
      "Tavastehus hamn ligger vid sjön Vanajavesi i en av Finlands äldsta inlandsstäder. Staden är känd för sin medeltida borg, Tavastehus slott, och som födelseplatsen för kompositören Jean Sibelius. Hamnen betjänar fritidsbåtar och är ansluten till stadens centrum med dess restauranger, butiker och kulturella attraktioner.",
    hints: [
      "Denna hamn ligger vid sjön Vanajavesi i en av Finlands äldsta inlandsstäder",
      "Staden är känd för sin medeltida borg",
      "Det är födelseplatsen för kompositören Jean Sibelius",
      "Stadens namn betyder bokstavligen 'Tavastehus' på svenska",
      "Namnet börjar med 'T' och har 10 bokstäver",
    ],
  },
  {
    id: 41,
    name: "Tammerfors Hamn",
    language: "sv",
    coordinates: { lat: 61.5, lng: 23.7667 },
    region: "Birkaland",
    type: ["Insjöhamn", "Sjöhamn"],
    notableFeature: "Industristadens hamn vid sjön Pyhäjärvi med restaurerade fabriksbyggnader",
    description:
      "Tammerfors hamn (Laukontori) ligger vid sjön Pyhäjärvi i Finlands största inlandsstad. Känd som 'Finlands Manchester' på grund av sitt industriella arv, staden är byggd mellan två sjöar förbundna av Tammerfors-forsen. Hamnområdet har restaurerade fabriksbyggnader, restauranger och ligger nära stadens centrum med dess butiker och kulturella attraktioner.",
    hints: [
      "Denna hamn ligger vid sjön Pyhäjärvi i Finlands största inlandsstad",
      "Staden är känd som 'Finlands Manchester' på grund av sitt industriella arv",
      "Den är byggd mellan två sjöar förbundna av en fors",
      "Hamnområdet har restaurerade fabriksbyggnader",
      "Stadens namn börjar med 'T' och har 10 bokstäver",
    ],
  },
  {
    id: 42,
    name: "Brahestad Hamn",
    language: "sv",
    coordinates: { lat: 64.6833, lng: 24.4833 },
    region: "Norra Österbotten",
    type: ["Handelshamn", "Gästhamn"],
    notableFeature: "Historisk kuststad med en välbevarad trähusgamla stad och industrihamn",
    description:
      "Brahestad hamn betjänar både industriell sjöfart och fritidsbåtar. Staden har en välbevarad trähusgamla stad, Pekkatori, och ett starkt maritimt arv som visas i dess sjöfartsmuseum. Gästhamnen erbjuder tjänster för besökande båtfarare och ligger inom gångavstånd från stadens centrum.",
    hints: [
      "Denna hamn betjänar en historisk kuststad med en välbevarad trähusgamla stad",
      "Staden har ett starkt maritimt arv och ett sjöfartsmuseum",
      "Den har både en industrihamn och en gästhamn",
      "Den ligger i Norra Österbotten vid Bottniska viken",
      "Det svenska namnet börjar med 'B' och har 9 bokstäver",
    ],
  },
  {
    id: 43,
    name: "Karleby Hamn",
    language: "sv",
    coordinates: { lat: 63.8383, lng: 23.1317 },
    region: "Mellersta Österbotten",
    type: ["Handelshamn", "Gästhamn"],
    notableFeature: "Viktig exporthamn med en välbevarad trähusgamla stad",
    description:
      "Karleby hamn (Kokkola på finska) är en viktig exporthamn vid Bottniska viken. Staden har en välbevarad trähusgamla stad, Neristan, och ett starkt maritimt och handelsarv. Gästhamnen erbjuder tjänster för besökande båtfarare och ligger nära stadens centrum med dess butiker, restauranger och kulturella attraktioner.",
    hints: [
      "Denna hamn är en viktig exporthamn vid Bottniska viken",
      "Staden har en välbevarad trähusgamla stad kallad Neristan",
      "Det är huvudstaden i Mellersta Österbottenregionen",
      "Staden är officiellt tvåspråkig med både finska och svenska namn",
      "Det svenska namnet börjar med 'K' och har 7 bokstäver",
    ],
  },
  {
    id: 44,
    name: "Jakobstad Hamn",
    language: "sv",
    coordinates: { lat: 63.6667, lng: 22.7 },
    region: "Österbotten",
    type: ["Handelshamn", "Gästhamn"],
    notableFeature: "Tvåspråkig kuststad med en stark maritim och skeppsbyggnadstradition",
    description:
      "Jakobstad hamn (Pietarsaari på finska) betjänar en tvåspråkig kuststad med en stark maritim och skeppsbyggnadstradition. Gästhamnen erbjuder bra service för besökande båtfarare och ligger nära stadens centrum med dess butiker, restauranger och attraktioner inklusive den botaniska trädgården Skata och Nanoq arktiska museet.",
    hints: [
      "Denna hamn betjänar en tvåspråkig kuststad med en stark maritim tradition",
      "Staden har en svensktalande majoritet och en finsktalande minoritet",
      "Den har en botanisk trädgård kallad Skata och Nanoq arktiska museet",
      "Staden namngavs efter Jacob De la Gardie på 1600-talet",
      "Det svenska namnet börjar med 'J', men den är också känd under sitt finska namn 'Pietarsaari'",
    ],
  },
  {
    id: 45,
    name: "Nykarleby Hamn",
    language: "sv",
    coordinates: { lat: 63.5222, lng: 22.5303 },
    region: "Österbotten",
    type: ["Flodhamn", "Gästhamn"],
    notableFeature: "Liten tvåspråkig stad vid mynningen av Lappo å",
    description:
      "Nykarleby hamn (Uusikaarlepyy på finska) ligger vid mynningen av Lappo å. Denna lilla, övervägande svensktalande stad har ett charmigt centrum med träbyggnader och ett rikt kulturarv. Den lilla gästhamnen erbjuder grundläggande tjänster för besökande båtfarare.",
    hints: [
      "Denna hamn ligger vid mynningen av Lappo å",
      "Staden är övervägande svensktalande",
      "Det är en av de minsta städerna i Finland",
      "Poeten Zacharias Topelius föddes här",
      "Det svenska namnet börjar med 'N', men den är också känd under sitt finska namn 'Uusikaarlepyy'",
    ],
  },
  {
    id: 46,
    name: "Kalajoki Hamn",
    language: "sv",
    coordinates: { lat: 64.2567, lng: 23.9486 },
    region: "Norra Österbotten",
    type: ["Gästhamn", "Badort"],
    notableFeature: "Populärt turistmål med omfattande sandstränder",
    description:
      "Kalajoki hamn betjänar ett populärt kustturistmål känt för sina omfattande sandstränder, sanddyner och semesterorter. Gästhamnen erbjuder bra service för besökande båtfarare och ligger nära strandområdet med dess restauranger, aktiviteter och boendealternativ.",
    hints: [
      "Denna hamn betjänar ett populärt kustturistmål känt för sandstränder",
      "Området har ovanliga sanddyner för Finland",
      "Det är en populär sommarsemesterort",
      "Den ligger i Norra Österbotten vid Bottniska viken",
      "Namnet börjar med 'K' och betyder 'fiskflod' på finska",
    ],
  },
  {
    id: 47,
    name: "Villmanstrand Hamn",
    language: "sv",
    coordinates: { lat: 61.0681, lng: 28.1889 },
    region: "Södra Karelen",
    type: ["Insjöhamn", "Kanalport"],
    notableFeature: "Livligt hamnområde nära en fästning, port till Saima kanal",
    description:
      "Villmanstrand hamn är en livlig insjöhamn på Saimen, som fungerar som en port till Saima kanal som ansluter till Ryssland. Staden har en historisk fästning och ett livligt hamnområde med restauranger, kryssningsfartyg och en marknad. Hamnen erbjuder bra service för fritidsbåtar som utforskar Saimenvattensystemet.",
    hints: [
      "Denna hamn är på Saimen och fungerar som en port till en kanal som ansluter till Ryssland",
      "Staden har en historisk fästning som överblickar hamnen",
      "Den har ett livligt hamnområde med restauranger och en marknad",
      "Staden är känd för sitt tekniska universitet",
      "Namnet slutar med 'strand' som betyder 'strand' på svenska",
    ],
  },
  {
    id: 48,
    name: "Imatra Hamn",
    language: "sv",
    coordinates: { lat: 61.1722, lng: 28.7756 },
    region: "Södra Karelen",
    type: ["Insjöhamn", "Flodhamn"],
    notableFeature: "Hamn nära de kraftfulla Imatra-forsarna på ryska gränsen",
    description:
      "Imatra hamn ligger på Saimen nära de kraftfulla Imatra-forsarna och nära den ryska gränsen. Staden utvecklades runt ett vattenkraftverk och har ett unikt industriellt arv. Hamnen betjänar fritidsbåtar som utforskar de östra delarna av Saimenvattensystemet.",
    hints: [
      "Denna hamn är på Saimen nära kraftfulla forsar",
      "Staden är mycket nära den ryska gränsen",
      "Den utvecklades runt ett vattenkraftverk",
      "Forsarna är en berömd naturattraktion som har inspirerat konstnärer",
      "Namnet börjar med 'I' och har 6 bokstäver",
    ],
  },
  {
    id: 49,
    name: "Kemi-Torneå Hamn",
    language: "sv",
    coordinates: { lat: 65.7361, lng: 24.5653 },
    region: "Lappland",
    type: ["Industrihamn", "Handelshamn"],
    notableFeature: "Stor industrihamn som betjänar skogs- och gruvindustrierna i Lappland",
    description:
      "Kemi-Torneå hamn är ett stort industrihamnkomplex som betjänar skogs- och gruvindustrierna i Lappland. Området är känt för sina massa- och pappersbruk, stålproduktion och som ett logistiknav för norra Finland. Hamnen hanterar bulklast, containrar och industriprodukter.",
    hints: [
      "Denna hamn är ett stort industrihamnkomplex i Lappland",
      "Den betjänar skogs- och gruvindustrierna i norra Finland",
      "Området är känt för massa- och pappersbruk och stålproduktion",
      "Den är uppkallad efter två grannstäder",
      "En av städerna är känd för sitt årliga snöslott",
    ],
  },
  {
    id: 50,
    name: "Rovaniemi Hamn",
    language: "sv",
    coordinates: { lat: 66.5, lng: 25.7167 },
    region: "Lappland",
    type: ["Flodhamn", "Arktisk hamn"],
    notableFeature: "Hamn i 'jultomtens officiella hemstad' vid polcirkeln",
    description:
      "Rovaniemi hamn ligger vid Kemi älv i huvudstaden för finska Lappland, känd som 'jultomtens officiella hemstad.' Staden ligger vid polcirkeln och fungerar som en port till den norra vildmarken. Den lilla hamnen betjänar flodbåtar och ligger nära stadens centrum med dess butiker, restauranger och attraktioner inklusive Arktikum-museet.",
    hints: [
      "Denna hamn ligger vid Kemi älv i huvudstaden för finska Lappland",
      "Staden är känd som 'jultomtens officiella hemstad'",
      "Den ligger vid polcirkeln",
      "Staden byggdes nästan helt om efter andra världskriget",
      "Namnet börjar med 'R' och har 9 bokstäver",
    ],
  },
  {
    id: 51,
    name: "Pargas Hamn",
    language: "sv",
    coordinates: { lat: 60.3, lng: 22.3 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Industrihamn"],
    notableFeature: "Port till Skärgårdsringen med kalkstensindustriarv",
    description:
      "Pargas hamn (Parainen på finska) fungerar som en port till Skärgårdsringen, en populär rutt som förbinder öarna i Skärgårdshavet. Staden har ett starkt kalkstensindustriarv med ett stort stenbrott och cementfabrik. Gästhamnen erbjuder bra service för båtfarare och ligger nära stadens centrum med dess butiker och restauranger.",
    hints: [
      "Denna hamn fungerar som en port till Skärgårdsringen",
      "Staden har ett starkt kalkstensindustriarv med ett stort stenbrott",
      "Det är en tvåspråkig kommun med både finska och svenska namn",
      "Det är utgångspunkten för att utforska Skärgårdshavet med bil och färja",
      "Det svenska namnet börjar med 'P', det finska namnet är 'Parainen'",
    ],
  },
  {
    id: 52,
    name: "Korpo Hamn",
    language: "sv",
    coordinates: { lat: 60.1667, lng: 21.5833 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Färjehamn"],
    notableFeature: "Viktigt stopp på Skärgårdsringen med historisk träkyrka",
    description:
      "Korpo hamn (Korppoo på finska) är ett viktigt stopp på Skärgårdsringen, som betjänar både fritidsbåtar och bilfärjor. Ön har en historisk träkyrka från 1400-talet och en traditionell skärgårdsby. Gästhamnen erbjuder bra service och ligger nära byns centrum med dess små butiker och restauranger.",
    hints: [
      "Denna hamn är ett viktigt stopp på Skärgårdsringen",
      "Ön har en historisk träkyrka från 1400-talet",
      "Det är en tvåspråkig kommun med både finska och svenska namn",
      "Den är en del av staden Pargas/Parainen sedan 2009",
      "Det svenska namnet börjar med 'K', det finska namnet är 'Korppoo'",
    ],
  },
  {
    id: 53,
    name: "Nagu Hamn",
    language: "sv",
    coordinates: { lat: 60.1917, lng: 21.9083 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Skärgårdsnav"],
    notableFeature: "Populärt skärgårdsnav med en livlig gästhamn och historisk kyrka",
    description:
      "Nagu hamn (Nauvo på finska) är en av de mest populära gästhamnarna i Skärgårdshavet, som fungerar som ett nav för båtfarare som utforskar området. Ön har en medeltida stenkyrka och ett livligt bycentrum. Gästhamnen erbjuder utmärkt service och är omgiven av restauranger, caféer och butiker, vilket skapar en livlig maritim atmosfär under sommaren.",
    hints: [
      "Denna hamn är en av de mest populära gästhamnarna i Skärgårdshavet",
      "Ön har en medeltida stenkyrka",
      "Den har ett livligt bycentrum med restauranger och butiker",
      "Det är en tvåspråkig kommun med både finska och svenska namn",
      "Det svenska namnet börjar med 'N', det finska namnet är 'Nauvo'",
    ],
  },
  {
    id: 54,
    name: "Houtskär Hamn",
    language: "sv",
    coordinates: { lat: 60.2167, lng: 21.3667 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Traditionell"],
    notableFeature: "Avlägsen skärgårdsö med traditionella trähus och kyrka",
    description:
      "Houtskär hamn (Houtskari på finska) betjänar en avlägsen ö i yttre Skärgårdshavet. Ön har traditionella trähus, en träkyrka från 1700-talet och vackra skärgårdslandskap. Gästhamnen erbjuder grundläggande service för besökande båtfarare och ligger nära det lilla bycentrumet.",
    hints: [
      "Denna hamn betjänar en avlägsen ö i yttre Skärgårdshavet",
      "Ön har traditionella trähus och en träkyrka",
      "Det är ett övervägande svensktalande område",
      "Den är en del av staden Pargas/Parainen sedan 2009",
      "Det svenska namnet börjar med 'H', det finska namnet är 'Houtskari'",
    ],
  },
  {
    id: 55,
    name: "Iniö Hamn",
    language: "sv",
    coordinates: { lat: 60.4, lng: 21.4167 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Avlägsen ö"],
    notableFeature: "Finlands minsta tidigare kommun med traditionell skärgårdskultur",
    description:
      "Iniö hamn betjänar en av de mest avlägsna bebodda ögrupperna i Skärgårdshavet. Tidigare Finlands minsta kommun, området upprätthåller en stark traditionell skärgårdskultur. Gästhamnen erbjuder grundläggande service för besökande båtfarare och ligger nära det lilla bycentrumet med dess kyrka och lokala service.",
    hints: [
      "Denna hamn betjänar en av de mest avlägsna bebodda ögrupperna i Skärgårdshavet",
      "Det var tidigare Finlands minsta kommun",
      "Området upprätthåller en stark traditionell skärgårdskultur",
      "Den är en del av staden Pargas/Parainen sedan 2009",
      "Namnet är detsamma på både finska och svenska",
    ],
  },
  {
    id: 56,
    name: "Kasnäs Hamn",
    language: "sv",
    coordinates: { lat: 59.9167, lng: 22.4167 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Naturturism"],
    notableFeature: "Modern marina nära Skärgårdshavets nationalparks besökscentrum",
    description:
      "Kasnäs hamn är en modern marina belägen vid spetsen av Kimitoön-halvön, som fungerar som en port till Skärgårdshavets nationalpark. Området har Blåmusslan besökscentrum, ett spahotell och utmärkta faciliteter för båtfarare. Hamnen är en populär utgångspunkt för att utforska de södra delarna av Skärgårdshavet.",
    hints: [
      "Denna hamn ligger vid spetsen av Kimitoön-halvön",
      "Den fungerar som en port till Skärgårdshavets nationalpark",
      "Området har Blåmusslan besökscentrum",
      "Den har ett spahotell och utmärkta faciliteter för båtfarare",
      "Namnet börjar med 'K' och slutar med 's'",
    ],
  },
  {
    id: 57,
    name: "Gustavs Hamn",
    language: "sv",
    coordinates: { lat: 60.55, lng: 21.3667 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Fiskarby"],
    notableFeature: "Historisk fiskarby vid norra kanten av Skärgårdshavet",
    description:
      "Gustavs hamn (Kustavi på finska) betjänar en historisk fiskarby vid norra kanten av Skärgårdshavet. Området har ett starkt maritimt arv och är känt för sin traditionella fiskrökning. Gästhamnen erbjuder bra service för besökande båtfarare och ligger nära byns centrum med dess restauranger specialiserade på lokala fiskrätter.",
    hints: [
      "Denna hamn betjänar en historisk fiskarby vid norra kanten av Skärgårdshavet",
      "Området har ett starkt maritimt arv och är känt för traditionell fiskrökning",
      "Det är ett populärt sommarmål med många sommarstugor",
      "Kommunen har fler öar än fastland",
      "Det svenska namnet börjar med 'G', det finska namnet är 'Kustavi'",
    ],
  },
  {
    id: 58,
    name: "Rimito Hamn",
    language: "sv",
    coordinates: { lat: 60.3833, lng: 21.9333 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Fiskarby"],
    notableFeature: "Traditionell fiskarby med medeltida stenkyrka",
    description:
      "Rimito hamn (Rymättylä på finska) betjänar en traditionell fiskarby på ön med samma namn. Området har ett starkt fiskarv och har en medeltida stenkyrka från 1400-talet. Gästhamnen erbjuder service för besökande båtfarare och ligger nära byns centrum med dess små butiker och restauranger.",
    hints: [
      "Denna hamn betjänar en traditionell fiskarby på en ö",
      "Området har ett starkt fiskarv",
      "Den har en medeltida stenkyrka från 1400-talet",
      "Den är nu en del av staden Nådendal",
      "Det svenska namnet börjar med 'R', det finska namnet är 'Rymättylä'",
    ],
  },
  {
    id: 59,
    name: "Velkua Hamn",
    language: "sv",
    coordinates: { lat: 60.45, lng: 21.6833 },
    region: "Skärgårdshavet",
    type: ["Gästhamn", "Ösamhälle"],
    notableFeature: "Idylliskt ösamhälle med träkyrka och traditionella landskap",
    description:
      "Velkua hamn betjänar ett idylliskt ösamhälle bestående av flera bebodda öar. Området har en träkyrka från 1700-talet och traditionella skärgårdslandskap. Den lilla gästhamnen erbjuder grundläggande service för besökande båtfarare och ligger nära huvudbyn med dess lokala service.",
    hints: [
      "Denna hamn betjänar ett idylliskt ösamhälle bestående av flera bebodda öar",
      "Området har en träkyrka från 1700-talet",
      "Det var tidigare en av Finlands minsta kommuner",
      "Den är nu en del av staden Nådendal",
      "Namnet börjar med 'V' och har 6 bokstäver",
    ],
  },
  {
    id: 60,
    name: "Sastmola Hamn",
    language: "sv",
    coordinates: { lat: 61.8583, lng: 21.4917 },
    region: "Satakunta",
    type: ["Fiskehamn", "Gästhamn"],
    notableFeature: "Traditionell fiskestad med träbåthus och starkt maritimt arv",
    description:
      "Sastmola hamn (Merikarvia på finska) betjänar en traditionell fiskestad vid Bottniska vikens kust. Området är känt för sina träbåthus, starka fisketradition och en älv berömd för laxfiske. Gästhamnen erbjuder service för besökande båtfarare och ligger nära stadens centrum med dess träkyrka och lokala service.",
    hints: [
      "Denna hamn betjänar en traditionell fiskestad vid Bottniska vikens kust",
      "Området är känt för sina träbåthus och starka fisketradition",
      "Den har en älv berömd för laxfiske",
      "Stadens finska namn betyder bokstavligen 'havsrev' på finska",
      "Det svenska namnet börjar med 'S' och har 8 bokstäver",
    ],
  },
]

// Function to fetch harbor data
export async function fetchHarborData(language = "sv") {
  // In a real app, this would be an API call
  return new Promise((resolve) => {
    // Simulate network delay
    setTimeout(() => {
      resolve(harbors)
    }, 800)
  })
}

